export const DASHBOARD_LIMITS = {
  TOP_CUSTOMERS: 10,
  OVERDUE_ORDERS: 20,
  EXPIRING_CONTRACTS: 10,
  PENDING_PAYMENTS: 20,
  UNDERPERFORMING_KPIS: 10,
  REVENUE_BY_PERIOD_MAX: 12,
  TOP_PRODUCTS: 10,
  LEADERBOARD_MAX: 20,
  KPIS_PER_CATEGORY: 5,
} as const;
