export enum ConfigVariablesGroup {
  ServerConfig = 'server-config',
  RateLimiting = 'rate-limiting',
  StorageConfig = 'storage-config',
  GoogleAuth = 'google-auth',
  MicrosoftAuth = 'microsoft-auth',
  EmailSettings = 'email-settings',
  Logging = 'logging',
  Metering = 'metering',
  ExceptionHandler = 'exception-handler',
  Other = 'other',
  BillingConfig = 'billing-config',
  CaptchaConfig = 'captcha-config',
  CloudflareConfig = 'cloudflare-config',
  LLM = 'llm',
  ServerlessConfig = 'serverless-config',
  SSL = 'ssl',
  SupportChatConfig = 'support-chat-config',
  AnalyticsConfig = 'audit-config',
  TokensDuration = 'tokens-duration',
  TwoFactorAuthentication = 'two-factor-authentication',
  // MKT Core Groups
  MktInvoice = 'mkt-invoice',
  MktPayment = 'mkt-payment',
  MktOAuth2 = 'mkt-oauth2',
  MktProductSync = 'mkt-product-sync',
  MktOrder = 'mkt-order',
  MktRbac = 'mkt-rbac',
  MktGeneral = 'mkt-general',
}
