// Permission Action Keys aligned with 11-level hierarchy and Enterprise features
export const PERMISSION_ACTION_KEYS = {
  // Basic CRUD operations
  READ: 'READ',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',

  // Advanced operations
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT',
  SHARE: 'SHARE',
  PUBLISH: 'PUBLISH',
  ARCHIVE: 'ARCHIVE',
  RESTORE: 'RESTORE',

  // Approval operations
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  ESCALATE: 'ESCALATE',

  // System operations
  CONFIGURE: 'CONFIGURE',
  MONITOR: 'MONITOR',
  AUDIT: 'AUDIT',

  // Bulk operations
  BULK_CREATE: 'BULK_CREATE',
  BULK_UPDATE: 'BULK_UPDATE',
  BULK_DELETE: 'BULK_DELETE',
  BULK_EXPORT: 'BULK_EXPORT',

  // Team Management operations (for hierarchy levels)
  MANAGE_TEAM: 'MANAGE_TEAM',
  ASSIGN_TASKS: 'ASSIGN_TASKS',
  VIEW_TEAM_REPORTS: 'VIEW_TEAM_REPORTS',
  CONDUCT_REVIEWS: 'CONDUCT_REVIEWS',

  // Financial operations (sensitive for higher levels)
  ACCESS_SALARY_DATA: 'ACCESS_SALARY_DATA',
  APPROVE_TRANSACTIONS: 'APPROVE_TRANSACTIONS',
  VIEW_FINANCIAL_REPORTS: 'VIEW_FINANCIAL_REPORTS',
  BUDGET_MANAGEMENT: 'BUDGET_MANAGEMENT',

  // Sensitive data access (hierarchy-based)
  ACCESS_SENSITIVE_DATA: 'ACCESS_SENSITIVE_DATA',
  VIEW_CONFIDENTIAL_INFO: 'VIEW_CONFIDENTIAL_INFO',
  BYPASS_WORKFLOW_APPROVAL: 'BYPASS_WORKFLOW_APPROVAL',

  // Customer Management operations (CRM-specific)
  ASSIGN_CUSTOMER: 'ASSIGN_CUSTOMER',
  TRANSFER_CUSTOMER: 'TRANSFER_CUSTOMER',
  MERGE_CUSTOMERS: 'MERGE_CUSTOMERS',
  CONVERT_LEAD: 'CONVERT_LEAD',

  // Communication operations (CRM-specific)
  SEND_EMAIL: 'SEND_EMAIL',
  MAKE_CALL: 'MAKE_CALL',
  SEND_SMS: 'SEND_SMS',
  SCHEDULE_MEETING: 'SCHEDULE_MEETING',

  // Deal Management operations (CRM-specific)
  CLOSE_DEAL: 'CLOSE_DEAL',
  CHANGE_DEAL_STAGE: 'CHANGE_DEAL_STAGE',
  APPROVE_DISCOUNT: 'APPROVE_DISCOUNT',

  // Reporting operations (CRM-specific)
  CREATE_REPORT: 'CREATE_REPORT',
  SCHEDULE_REPORT: 'SCHEDULE_REPORT',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  EXPORT_ANALYTICS: 'EXPORT_ANALYTICS',

  // User Management operations (CRM-specific)
  MANAGE_USERS: 'MANAGE_USERS',
  ASSIGN_ROLES: 'ASSIGN_ROLES',
  RESET_PASSWORD: 'RESET_PASSWORD',
  VIEW_USER_ACTIVITY: 'VIEW_USER_ACTIVITY',

  // Automation operations (CRM-specific)
  CONFIGURE_INTEGRATION: 'CONFIGURE_INTEGRATION',
  CREATE_WORKFLOW: 'CREATE_WORKFLOW',
  EXECUTE_API: 'EXECUTE_API',

  // Security & Compliance Operations (Enterprise)
  MANAGE_SECURITY_POLICIES: 'MANAGE_SECURITY_POLICIES',
  CONFIGURE_ACCESS_CONTROLS: 'CONFIGURE_ACCESS_CONTROLS',
  VIEW_SECURITY_LOGS: 'VIEW_SECURITY_LOGS',
  CONDUCT_SECURITY_AUDIT: 'CONDUCT_SECURITY_AUDIT',
  MANAGE_COMPLIANCE_RULES: 'MANAGE_COMPLIANCE_RULES',
  GENERATE_COMPLIANCE_REPORT: 'GENERATE_COMPLIANCE_REPORT',
  CLASSIFY_DATA: 'CLASSIFY_DATA',
  MANAGE_DATA_RETENTION: 'MANAGE_DATA_RETENTION',
  HANDLE_PRIVACY_REQUEST: 'HANDLE_PRIVACY_REQUEST',
  CONFIGURE_DATA_MASKING: 'CONFIGURE_DATA_MASKING',

  // Integration & API Management (Enterprise)
  CREATE_API_KEY: 'CREATE_API_KEY',
  MANAGE_API_RATE_LIMITS: 'MANAGE_API_RATE_LIMITS',
  CONFIGURE_OAUTH: 'CONFIGURE_OAUTH',
  MANAGE_INTEGRATIONS: 'MANAGE_INTEGRATIONS',
  CREATE_WEBHOOK: 'CREATE_WEBHOOK',
  CONFIGURE_WEBHOOK: 'CONFIGURE_WEBHOOK',
  ACCESS_THIRD_PARTY_SERVICE: 'ACCESS_THIRD_PARTY_SERVICE',
  MANAGE_SERVICE_CONNECTIONS: 'MANAGE_SERVICE_CONNECTIONS',

  // Advanced Enterprise Features
  CREATE_COMPLEX_WORKFLOW: 'CREATE_COMPLEX_WORKFLOW',
  ORCHESTRATE_PROCESSES: 'ORCHESTRATE_PROCESSES',
  CREATE_BI_DASHBOARD: 'CREATE_BI_DASHBOARD',
  ACCESS_BI_TOOLS: 'ACCESS_BI_TOOLS',
  PERFORM_ADVANCED_ANALYTICS: 'PERFORM_ADVANCED_ANALYTICS',
  CREATE_PREDICTIVE_MODEL: 'CREATE_PREDICTIVE_MODEL',
  CREATE_CUSTOM_FIELDS: 'CREATE_CUSTOM_FIELDS',
  DEVELOP_CUSTOM_APPS: 'DEVELOP_CUSTOM_APPS',
  MANAGE_TENANTS: 'MANAGE_TENANTS',
  CONFIGURE_MULTI_TENANCY: 'CONFIGURE_MULTI_TENANCY',

  // Operational Excellence (Enterprise)
  CONFIGURE_MONITORING: 'CONFIGURE_MONITORING',
  VIEW_SYSTEM_METRICS: 'VIEW_SYSTEM_METRICS',
  MANAGE_ALERTS: 'MANAGE_ALERTS',
  BACKUP_DATA: 'BACKUP_DATA',
  RESTORE_BACKUP: 'RESTORE_BACKUP',
  CONFIGURE_DISASTER_RECOVERY: 'CONFIGURE_DISASTER_RECOVERY',
  OPTIMIZE_PERFORMANCE: 'OPTIMIZE_PERFORMANCE',
  TUNE_DATABASE: 'TUNE_DATABASE',
  PLAN_CAPACITY: 'PLAN_CAPACITY',
  MANAGE_RESOURCES: 'MANAGE_RESOURCES',

  // Data & Content Management (Enterprise)
  MIGRATE_DATA: 'MIGRATE_DATA',
  TRANSFORM_DATA: 'TRANSFORM_DATA',
  MANAGE_CONTENT_LIFECYCLE: 'MANAGE_CONTENT_LIFECYCLE',
  PUBLISH_CONTENT: 'PUBLISH_CONTENT',
  MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',
  VERSION_CONTROL_DOCUMENTS: 'VERSION_CONTROL_DOCUMENTS',
  MANAGE_KNOWLEDGE_BASE: 'MANAGE_KNOWLEDGE_BASE',
  CURATE_KNOWLEDGE: 'CURATE_KNOWLEDGE',

  // Advanced CRM & Sales Operations (Enterprise)
  MANAGE_TERRITORIES: 'MANAGE_TERRITORIES',
  ASSIGN_TERRITORIES: 'ASSIGN_TERRITORIES',
  SET_QUOTAS: 'SET_QUOTAS',
  TRACK_QUOTA_PERFORMANCE: 'TRACK_QUOTA_PERFORMANCE',
  CALCULATE_COMMISSION: 'CALCULATE_COMMISSION',
  APPROVE_COMMISSION: 'APPROVE_COMMISSION',
  CREATE_FORECAST: 'CREATE_FORECAST',
  ANALYZE_FORECAST: 'ANALYZE_FORECAST',

  // Multi-level Approval Workflows (Enterprise)
  CREATE_APPROVAL_CHAIN: 'CREATE_APPROVAL_CHAIN',
  CONFIGURE_APPROVAL_RULES: 'CONFIGURE_APPROVAL_RULES',
  MANAGE_ESCALATION_RULES: 'MANAGE_ESCALATION_RULES',
  HANDLE_ESCALATION: 'HANDLE_ESCALATION',
  DELEGATE_PERMISSIONS: 'DELEGATE_PERMISSIONS',
  MANAGE_DELEGATION: 'MANAGE_DELEGATION',
} as const;

// Risk Levels
export const PERMISSION_RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;
