/**
 * Customer Block Pre-Query Hooks
 *
 * Blocks specific auto-generated GraphQL operations on customer entities.
 * Forces users to use custom resolvers for certain operations.
 *
 * Entities và operations bị block:
 * - mktCustomer: ALL operations (use CustomerQueryResolver, CustomerMutationResolver)
 * - mktCustomerTierHistory: ALL WRITE operations (auto-generated by system)
 *
 * Entities không bị block (sử dụng auto-generated GraphQL):
 * - mktTag: Basic master data CRUD
 * - mktCustomerTag: Junction table managed via auto-generated operations
 * - mktCustomerNote: Auto-generated + custom resolvers (customerNoteList, customerNoteCreate, etc.)
 */

import {
  BlockHookConfig,
  createBlockHooks,
  WRITE_OPERATIONS,
} from 'src/mkt-core/common/hooks';
// Import from objects barrel export for single source of truth
import {
  MKT_CUSTOMER_ENTITY_NAME,
  MKT_CUSTOMER_TIER_HISTORY_ENTITY_NAME,
} from 'src/mkt-core/customer/objects';

// ============================================
// BLOCK HOOK CONFIGURATIONS
// ============================================

/**
 * Block hook configuration for mktCustomer entity
 * Block TẤT CẢ operations - phải dùng custom resolvers
 */
export const CUSTOMER_BLOCK_CONFIG: BlockHookConfig = {
  entityName: MKT_CUSTOMER_ENTITY_NAME,
  logContext: 'Customer:BlockHook',
  blockedMessage:
    'This operation is disabled. Use custom Customer resolvers instead (getCustomerById, createCustomer, updateCustomer, etc.)',
  // Not specifying blockedOperations = block ALL operations
};

/**
 * Block hook configuration for mktCustomerTierHistory entity
 * Block TẤT CẢ write operations - được tự động generate bởi system
 */
export const CUSTOMER_TIER_HISTORY_BLOCK_CONFIG: BlockHookConfig = {
  entityName: MKT_CUSTOMER_TIER_HISTORY_ENTITY_NAME,
  logContext: 'CustomerTierHistory:BlockHook',
  blockedMessage:
    'Direct tier history operations are disabled. Tier history is automatically managed by the system.',
  blockedOperations: [...WRITE_OPERATIONS],
};

// ============================================
// GENERATE BLOCK HOOKS
// ============================================

/**
 * mktCustomer block hooks (all 13 operations)
 */
const customerBlockResult = createBlockHooks(CUSTOMER_BLOCK_CONFIG);

/**
 * mktCustomerTierHistory block hooks (all write operations)
 */
const tierHistoryBlockResult = createBlockHooks(
  CUSTOMER_TIER_HISTORY_BLOCK_CONFIG,
);

// ============================================
// EXPORTS
// ============================================

/**
 * All Customer module block hook providers
 * Import this into CustomerModule
 */
export const CUSTOMER_BLOCK_HOOKS = [
  ...customerBlockResult.providers,
  ...tierHistoryBlockResult.providers,
];

/**
 * Individual block hook providers for specific entities
 */
export const CUSTOMER_ENTITY_BLOCK_HOOKS = customerBlockResult.providers;
export const TIER_HISTORY_ENTITY_BLOCK_HOOKS = tierHistoryBlockResult.providers;

/**
 * List of all blocked operation strings for reference
 */
export const CUSTOMER_BLOCKED_OPERATIONS = [
  ...customerBlockResult.blockedOperations,
  ...tierHistoryBlockResult.blockedOperations,
];
