export enum CacheStorageNamespace {
  ModuleMessaging = 'module:messaging',
  ModuleCalendar = 'module:calendar',
  ModuleWorkflow = 'module:workflow',
  EngineWorkspace = 'engine:workspace',
  EngineLock = 'engine:lock',
  EngineHealth = 'engine:health',
  MktOAuth2 = 'mkt:oauth2',
  MktProduct = 'mkt:product',
  MktPromotion = 'mkt:promotion',
  MktOrder = 'mkt:order',
  MktDepartment = 'mkt:department',
  MktAuth = 'mkt:auth',
  MktDashboard = 'mkt:dashboard',
  // RBAC v2.0 dedicated namespaces
  RbacPermission = 'rbac:permission',
  RbacUser = 'rbac:user',
  RbacTemplate = 'rbac:template',
  RbacPolicy = 'rbac:policy',
}
