import { WORKSPACE_MEMBER_DATA_SEED_IDS } from 'src/engine/workspace-manager/dev-seeder/data/constants/workspace-member-data-seeds.constant';
import {
  MKT_CONTRACT_STATUS,
  MKT_CONTRACT_TYPE,
} from 'src/mkt-core/contract/constants';
import { MKT_CUSTOMER_DATA_SEEDS_IDS } from 'src/mkt-core/customer/constants';

export const MKT_CONTRACT_DATA_SEED_COLUMNS = [
  'id',
  'name',
  'contractNumber',
  'startDate',
  'endDate',
  'signedDate',
  'status',
  'contractType',
  'description',
  'position',
  'customerId',
  'createdById',
  'accountOwnerId',
];

export const MKT_CONTRACT_DATA_SEEDS_IDS = {
  ID_1: 'c1f5e779-7f5d-4da3-93c3-e306bbcf6a50',
  ID_2: 'f852a725-c8a3-4683-902f-1a048b6aa279',
  ID_3: '69df7cf8-4d11-45e1-961f-ed059a8dd1d8',
  ID_4: '9f38f34e-c811-4ed3-ba31-1917465da9af',
  ID_5: '5a581bd0-4601-463b-856b-c590287a56f8',
  ID_6: '5ee80222-779d-42bc-8a14-a10b5de4cfdc',
  ID_7: 'ed01c0c4-a3f5-4df3-99da-41b69792bc8d',
  ID_8: 'eca89e83-91c1-4d18-a598-7f8f45856e7f',
  ID_9: '7352a9a3-5b57-432f-a4c9-95ae681c8dbe',
  ID_10: '629efbad-cf9e-4f49-b2d3-7aa15ae464b6',
  ID_11: '91e86043-c08d-4752-a5c2-09936e75f5bf',
  ID_12: 'eaae4f37-e64c-490d-aa89-c83d6679f68a',
  ID_13: 'd82abed3-913b-447a-8bd3-aa62bf2cf8e7',
  ID_14: '7e3ab59d-18af-46b8-99bc-49f0c526ad89',
  ID_15: '581224fe-c663-4662-a23b-fa8d28f34555',
};

// prettier-ignore
export const MKT_CONTRACT_DATA_SEEDS = [
  // ── ACTIVE / ORIGIN ────────────────────────────────────────────────
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_1,
    name: 'Hợp đồng cung cấp phần mềm Microsoft Office 365',
    contractNumber: 'CT20240115001',
    startDate: '2024-01-15',
    endDate: '2025-01-14',
    signedDate: '2024-01-10',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng bản quyền phần mềm Microsoft Office 365 Business Premium, 50 licenses cho toàn bộ nhân sự công ty.',
    position: 1,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_5,
    name: 'Hợp đồng bảo trì hệ thống CNTT',
    contractNumber: 'CT20240101001',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    signedDate: '2023-12-20',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng bảo trì, vận hành hệ thống máy chủ, mạng nội bộ và hỗ trợ kỹ thuật 24/7 cho toàn bộ hạ tầng CNTT.',
    position: 2,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_6,
    name: 'Hợp đồng thuê máy trạm Dell Precision',
    contractNumber: 'CT20230915001',
    startDate: '2023-09-15',
    endDate: '2026-09-14',
    signedDate: '2023-09-10',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng thuê 30 máy trạm Dell Precision 5570 cho phòng Thiết kế và Kỹ thuật, bao gồm bảo hành và thay thế thiết bị.',
    position: 3,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_8,
    name: 'Hợp đồng nền tảng phân tích dữ liệu Tableau',
    contractNumber: 'CT20240401001',
    startDate: '2024-04-01',
    endDate: '2025-03-31',
    signedDate: '2024-03-25',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng sử dụng nền tảng Tableau Creator cho 10 người dùng, bao gồm đào tạo và hỗ trợ kỹ thuật.',
    position: 4,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_14,
    name: 'Hợp đồng nền tảng họp trực tuyến Zoom Pro',
    contractNumber: 'CT20240501001',
    startDate: '2024-05-01',
    endDate: '2025-04-30',
    signedDate: '2024-04-28',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng sử dụng Zoom Pro cho 100 người dùng, hỗ trợ cuộc họp không giới hạn thời gian và ghi hình trên cloud.',
    position: 5,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },

  // ── ACTIVE / RENEW ─────────────────────────────────────────────────
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_7,
    name: 'Hợp đồng gia hạn phần mềm bảo mật Norton Enterprise',
    contractNumber: 'CT20231201001',
    startDate: '2023-12-01',
    endDate: '2024-11-30',
    signedDate: '2023-11-25',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.RENEW,
    description: 'Gia hạn hợp đồng bảo mật Norton Enterprise năm thứ 2, bao gồm Endpoint Protection cho 80 thiết bị và bảo vệ email gateway.',
    position: 6,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_11,
    name: 'Hợp đồng gia hạn hosting AWS CloudFront',
    contractNumber: 'CT20240108001',
    startDate: '2024-01-08',
    endDate: '2025-01-07',
    signedDate: '2024-01-05',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.RENEW,
    description: 'Gia hạn dịch vụ website hosting và CDN AWS CloudFront, bao gồm SSL certificate và DDoS protection cho hệ thống web nội bộ.',
    position: 7,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
  },

  // ── ACTIVE / UPGRADE ───────────────────────────────────────────────
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_9,
    name: 'Hợp đồng nâng cấp Slack Business+',
    contractNumber: 'CT20240215001',
    startDate: '2024-02-15',
    endDate: '2025-02-14',
    signedDate: '2024-02-12',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.UPGRADE,
    description: 'Nâng cấp từ Slack Pro lên Business+ cho 120 người dùng, bao gồm SSO, SCIM provisioning và data export nâng cao.',
    position: 8,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_15,
    name: 'Hợp đồng nâng cấp GitHub Enterprise',
    contractNumber: 'CT20240615001',
    startDate: '2024-06-15',
    endDate: '2025-06-14',
    signedDate: '2024-06-10',
    status: MKT_CONTRACT_STATUS.ACTIVE,
    contractType: MKT_CONTRACT_TYPE.UPGRADE,
    description: 'Nâng cấp từ GitHub Team lên Enterprise cho 40 developer, bao gồm SAML SSO, audit log và Advanced Security.',
    position: 9,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
  },

  // ── PENDING_CONVERSION ─────────────────────────────────────────────
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_12,
    name: 'Hợp đồng phần mềm thiết kế Adobe Creative Cloud',
    contractNumber: 'CT20240320001',
    startDate: '2024-03-20',
    endDate: '2025-03-19',
    signedDate: null,
    status: MKT_CONTRACT_STATUS.PENDING_CONVERSION,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng Adobe Creative Cloud All Apps cho 15 designer, đang chờ chuyển đổi từ đơn hàng ĐH-2024-0320.',
    position: 10,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },

  // ── EXPIRED ────────────────────────────────────────────────────────
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_2,
    name: 'Hợp đồng hạ tầng Cloud AWS Enterprise',
    contractNumber: 'CT20230601001',
    startDate: '2023-06-01',
    endDate: '2024-05-31',
    signedDate: '2023-05-28',
    status: MKT_CONTRACT_STATUS.EXPIRED,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng sử dụng dịch vụ AWS Enterprise Support và Reserved Instances EC2, đã hết hạn và chờ gia hạn.',
    position: 11,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_13,
    name: 'Hợp đồng dịch vụ Email Marketing Mailchimp',
    contractNumber: 'CT20230801001',
    startDate: '2023-08-01',
    endDate: '2024-07-31',
    signedDate: '2023-07-25',
    status: MKT_CONTRACT_STATUS.EXPIRED,
    contractType: MKT_CONTRACT_TYPE.RENEW,
    description: 'Hợp đồng gia hạn Mailchimp Standard cho phòng Marketing, 10.000 contacts, đã hết hạn.',
    position: 12,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },

  // ── INACTIVE ───────────────────────────────────────────────────────
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_3,
    name: 'Hợp đồng nền tảng Marketing Automation HubSpot',
    contractNumber: 'CT20240210001',
    startDate: '2024-02-10',
    endDate: '2025-02-09',
    signedDate: '2024-02-05',
    status: MKT_CONTRACT_STATUS.INACTIVE,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng HubSpot Professional tạm ngừng theo yêu cầu khách hàng do tái cơ cấu phòng Marketing.',
    position: 13,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_10,
    name: 'Hợp đồng công cụ quản lý dự án Asana Premium',
    contractNumber: 'CT20231101001',
    startDate: '2023-11-01',
    endDate: '2024-10-31',
    signedDate: '2023-10-28',
    status: MKT_CONTRACT_STATUS.INACTIVE,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng Asana Premium cho 25 người dùng, tạm ngừng do công ty chuyển sang sử dụng Jira.',
    position: 14,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.CHURNED_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
  },

  // ── REVOKED ────────────────────────────────────────────────────────
  {
    id: MKT_CONTRACT_DATA_SEEDS_IDS.ID_4,
    name: 'Hợp đồng phần mềm CRM Salesforce Enterprise',
    contractNumber: 'CT20230601002',
    startDate: '2023-06-01',
    endDate: '2024-05-31',
    signedDate: '2023-05-25',
    status: MKT_CONTRACT_STATUS.REVOKED,
    contractType: MKT_CONTRACT_TYPE.ORIGIN,
    description: 'Hợp đồng Salesforce Enterprise bị thu hồi do vi phạm điều khoản sử dụng và không thanh toán đúng hạn.',
    position: 15,
    customerId: MKT_CUSTOMER_DATA_SEEDS_IDS.CHURNED_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
  },
];
