/**
 * Department Block Pre-Query Hooks
 *
 * Blocks specific auto-generated GraphQL operations on department entities.
 * Forces users to use custom resolvers (DepartmentMutationResolver).
 *
 * Entities và operations bị block:
 * - mktDepartment: createOne, updateOne (hierarchy management requires custom logic)
 * - mktDepartmentHierarchy: ALL write operations (managed by DepartmentMutationResolver)
 * - mktDepartmentAncestry: ALL write operations (auto-generated by system)
 * - mktDepartmentSubManager: ALL write operations (managed internally)
 *
 * All query operations (findMany, findOne) are still available via auto-generated GraphQL.
 */

import {
  BlockHookConfig,
  createBlockHooks,
  WRITE_OPERATIONS,
} from 'src/mkt-core/common/hooks';
import {
  MKT_DEPARTMENT_ENTITY_NAME,
  MKT_DEPARTMENT_HIERARCHY_ENTITY_NAME,
  MKT_DEPARTMENT_ANCESTRY_ENTITY_NAME,
  MKT_DEPARTMENT_SUB_MANAGER_ENTITY_NAME,
} from 'src/mkt-core/mkt-department/objects';

// ============================================
// BLOCK HOOK CONFIGURATIONS
// ============================================

/**
 * Block hook configuration for mktDepartment entity
 * Chỉ block CREATE_ONE và UPDATE_ONE vì cần quản lý hierarchy
 */
export const DEPARTMENT_BLOCK_CONFIG: BlockHookConfig = {
  entityName: MKT_DEPARTMENT_ENTITY_NAME,
  logContext: 'Department:BlockHook',
  blockedMessage:
    'This operation is disabled. Use custom Department resolvers instead (createDepartmentHierarchy, updateDepartmentHierarchy)',
  blockedOperations: ['CREATE_ONE', 'UPDATE_ONE'],
};

/**
 * Block hook configuration for mktDepartmentHierarchy entity
 * Block TẤT CẢ write operations - phải dùng DepartmentMutationResolver
 */
export const DEPARTMENT_HIERARCHY_BLOCK_CONFIG: BlockHookConfig = {
  entityName: MKT_DEPARTMENT_HIERARCHY_ENTITY_NAME,
  logContext: 'DepartmentHierarchy:BlockHook',
  blockedMessage:
    'Direct hierarchy operations are disabled. Use DepartmentMutationResolver to manage hierarchy.',
  blockedOperations: [...WRITE_OPERATIONS],
};

/**
 * Block hook configuration for mktDepartmentAncestry entity
 * Block TẤT CẢ write operations - được tự động generate bởi system
 */
export const DEPARTMENT_ANCESTRY_BLOCK_CONFIG: BlockHookConfig = {
  entityName: MKT_DEPARTMENT_ANCESTRY_ENTITY_NAME,
  logContext: 'DepartmentAncestry:BlockHook',
  blockedMessage:
    'Direct ancestry operations are disabled. Ancestry data is automatically managed by the system.',
  blockedOperations: [...WRITE_OPERATIONS],
};

/**
 * Block hook configuration for mktDepartmentSubManager entity
 * Block TẤT CẢ write operations - được quản lý nội bộ
 */
export const DEPARTMENT_SUB_MANAGER_BLOCK_CONFIG: BlockHookConfig = {
  entityName: MKT_DEPARTMENT_SUB_MANAGER_ENTITY_NAME,
  logContext: 'DepartmentSubManager:BlockHook',
  blockedMessage:
    'Direct sub-manager operations are disabled. Use Department management APIs instead.',
  blockedOperations: [...WRITE_OPERATIONS],
};

// ============================================
// GENERATE BLOCK HOOKS
// ============================================

/**
 * mktDepartment block hooks (2 hooks: createOne, updateOne)
 */
const departmentBlockResult = createBlockHooks(DEPARTMENT_BLOCK_CONFIG);

/**
 * mktDepartmentHierarchy block hooks (all write operations)
 */
const hierarchyBlockResult = createBlockHooks(
  DEPARTMENT_HIERARCHY_BLOCK_CONFIG,
);

/**
 * mktDepartmentAncestry block hooks (all write operations)
 */
const ancestryBlockResult = createBlockHooks(DEPARTMENT_ANCESTRY_BLOCK_CONFIG);

/**
 * mktDepartmentSubManager block hooks (all write operations)
 */
const subManagerBlockResult = createBlockHooks(
  DEPARTMENT_SUB_MANAGER_BLOCK_CONFIG,
);

// ============================================
// EXPORTS
// ============================================

/**
 * All Department module block hook providers
 * Import this into MktDepartmentModule
 */
export const DEPARTMENT_BLOCK_HOOKS = [
  ...departmentBlockResult.providers,
  ...hierarchyBlockResult.providers,
  ...ancestryBlockResult.providers,
  ...subManagerBlockResult.providers,
];

/**
 * Individual block hook providers for specific entities
 */
export const DEPARTMENT_ENTITY_BLOCK_HOOKS = departmentBlockResult.providers;
export const HIERARCHY_ENTITY_BLOCK_HOOKS = hierarchyBlockResult.providers;
export const ANCESTRY_ENTITY_BLOCK_HOOKS = ancestryBlockResult.providers;
export const SUB_MANAGER_ENTITY_BLOCK_HOOKS = subManagerBlockResult.providers;

/**
 * List of all blocked operation strings for reference
 */
export const DEPARTMENT_BLOCKED_OPERATIONS = [
  ...departmentBlockResult.blockedOperations,
  ...hierarchyBlockResult.blockedOperations,
  ...ancestryBlockResult.blockedOperations,
  ...subManagerBlockResult.blockedOperations,
];
