import {
  DEPARTMENT,
  MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS,
  MKT_DEPARTMENT_DATA_SEEDS_IDS,
  TEAM,
} from 'src/mkt-core/mkt-department/constants/mkt-department.constant';

export const MKT_DEPARTMENT_ANCESTRY_DATA_SEED_COLUMNS = [
  'id',
  'departmentId',
  'ancestorId',
  'distance',
  'computedAt',
  'departmentJoinId',
  'ancestorJoinId',
  'position',
];

const COMPUTED_AT = new Date('2024-01-01T00:00:00Z');

/**
 * Seed data for department ancestry records.
 * These records represent the parent-child relationships in the department hierarchy.
 * Distance = 1 means direct parent relationship.
 *
 * Hierarchy structure:
 * - SALES (Level 1)
 *   └── SALES_DOMESTIC, SALES_INTERNATIONAL, SALES_PARTNER, SALES_ONLINE (Level 2)
 * - SUPPORT (Level 1)
 *   └── SUPPORT_CUSTOMER, SUPPORT_TECHNICAL, SUPPORT_INTERNAL (Level 2)
 * - ACCOUNTING (Level 1)
 *   └── ACCOUNTING_PAYABLE, ACCOUNTING_RECEIVABLE, ACCOUNTING_AUDIT, ACCOUNTING_TAX (Level 2)
 * - HR (Level 1)
 *   └── HR_RECRUITMENT, HR_TRAINING, HR_PAYROLL (Level 2)
 * - TECH (Level 1)
 *   └── TECH_BACKEND, TECH_FRONTEND, TECH_DEVOPS, TECH_QA, TECH_DATA (Level 2)
 */
export const MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS = [
  // SALES team ancestries (teams -> SALES department, distance = 1)
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.SALES_DOMESTIC_TO_SALES,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_DOMESTIC],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_DOMESTIC],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    position: 1,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.SALES_INTERNATIONAL_TO_SALES,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_INTERNATIONAL],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_INTERNATIONAL],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    position: 2,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.SALES_PARTNER_TO_SALES,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_PARTNER],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_PARTNER],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    position: 3,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.SALES_ONLINE_TO_SALES,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_ONLINE],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_ONLINE],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    position: 4,
  },

  // SUPPORT team ancestries (teams -> SUPPORT department, distance = 1)
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.SUPPORT_CUSTOMER_TO_SUPPORT,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_CUSTOMER],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_CUSTOMER],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    position: 5,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.SUPPORT_TECHNICAL_TO_SUPPORT,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_TECHNICAL],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_TECHNICAL],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    position: 6,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.SUPPORT_INTERNAL_TO_SUPPORT,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_INTERNAL],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_INTERNAL],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    position: 7,
  },

  // ACCOUNTING team ancestries (teams -> ACCOUNTING department, distance = 1)
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.ACCOUNTING_PAYABLE_TO_ACCOUNTING,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_PAYABLE],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_PAYABLE],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    position: 8,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.ACCOUNTING_RECEIVABLE_TO_ACCOUNTING,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_RECEIVABLE],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_RECEIVABLE],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    position: 9,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.ACCOUNTING_AUDIT_TO_ACCOUNTING,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_AUDIT],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_AUDIT],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    position: 10,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.ACCOUNTING_TAX_TO_ACCOUNTING,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_TAX],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_TAX],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    position: 11,
  },

  // HR team ancestries (teams -> HR department, distance = 1)
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.HR_RECRUITMENT_TO_HR,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_RECRUITMENT],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_RECRUITMENT],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    position: 12,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.HR_TRAINING_TO_HR,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_TRAINING],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_TRAINING],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    position: 13,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.HR_PAYROLL_TO_HR,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_PAYROLL],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_PAYROLL],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    position: 14,
  },

  // TECH team ancestries (teams -> TECH department, distance = 1)
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.TECH_BACKEND_TO_TECH,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_BACKEND],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_BACKEND],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    position: 15,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.TECH_FRONTEND_TO_TECH,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_FRONTEND],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_FRONTEND],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    position: 16,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.TECH_DEVOPS_TO_TECH,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DEVOPS],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DEVOPS],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    position: 17,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.TECH_QA_TO_TECH,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_QA],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_QA],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    position: 18,
  },
  {
    id: MKT_DEPARTMENT_ANCESTRY_DATA_SEEDS_IDS.TECH_DATA_TO_TECH,
    departmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DATA],
    ancestorId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    distance: 1,
    computedAt: COMPUTED_AT,
    departmentJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DATA],
    ancestorJoinId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    position: 19,
  },
];
