import { WORKSPACE_MEMBER_DATA_SEED_IDS } from 'src/engine/workspace-manager/dev-seeder/data/constants/workspace-member-data-seeds.constant';
import { MKT_COMBO_DATA_SEEDS_IDS } from './mkt-combo-data-seeds.constants';
import { MKT_VARIANT_DATA_SEEDS_IDS } from './mkt-variant-data-seeds.constants';

type MktComboVariantDataSeed = {
  id: string;
  name: string;
  quantity: number;
  mktComboId: string;
  mktVariantId: string;

  position: number;
  createdBySource: string;
  createdByWorkspaceMemberId: string | null;
  createdByName: string;
};

// prettier-ignore
export const MKT_COMBO_VARIANT_DATA_SEED_COLUMNS: (keyof MktComboVariantDataSeed)[] = [
  'id',
  'name',
  'quantity',
  'mktComboId',
  'mktVariantId',
  'position',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
];

// prettier-ignore
export const MKT_COMBO_VARIANT_DATA_SEEDS_IDS = {
  ID_1: '357b466e-c269-40a7-8bc0-87b1df112e5a',
  ID_2: '79fff879-79d2-4e88-9023-4bd9380bd01d',
  ID_3: '1c46112b-6ccb-4564-8423-bc241c8de2c9',
  ID_4: '6876f7bf-22ef-4d46-8c3a-75b435ac220f',
  ID_5: '190827b6-df0a-4ff9-88cb-e41a87a1b65b',
  ID_6: '7208c42a-0f14-4d3e-824f-87c9f7b91484',
  ID_7: '784bfffe-f76f-4ea5-b2a0-ac6ada007c52',
  ID_8: 'e1169716-0b84-4c6c-b38d-264d095d128a',
  ID_9: 'b5a4be11-b19c-4095-8a6f-da8dc51aa5e5',
  ID_10: '285a38f8-aee3-4942-9015-b3372b8598bd',
  ID_11: 'df28cb75-9943-40aa-aa5d-c28aeff42489',
  ID_12: 'ee0baab1-1e57-4aa4-8df1-117368d5a24d',
  ID_13: '1bc7b318-7720-4549-bd67-f38c8f010428',
  ID_14: 'c2c4c08f-017e-4ba7-8c6a-36228106c86d',
  ID_15: 'd381cf02-f452-4879-a213-a3ec4ad2d9a1',
  ID_16: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  ID_17: 'b2c3d4e5-f6g7-8901-bcde-f23456789012',
  ID_18: 'c3d4e5f6-g7h8-9012-cdef-345678901234',
  ID_19: 'd4e5f6g7-h8i9-0123-defg-456789012345',
  ID_20: 'e5f6g7h8-i9j0-1234-efgh-567890123456',
  ID_21: 'f6g7h8i9-j0k1-2345-fghi-678901234567',
  ID_22: 'g7h8i9j0-k1l2-3456-ghij-789012345678',
  ID_23: 'h8i9j0k1-l2m3-4567-hijk-890123456789',
  ID_24: 'i9j0k1l2-m3n4-5678-ijkl-901234567890',
  ID_25: 'j0k1l2m3-n4o5-6789-jklm-012345678901',
  ID_26: 'k1l2m3n4-o5p6-7890-klmn-123456789012',
  ID_27: 'l2m3n4o5-p6q7-8901-lmno-234567890123',
  ID_28: 'm3n4o5p6-q7r8-9012-mnop-345678901234',
  ID_29: 'n4o5p6q7-r8s9-0123-nopq-456789012345',
  ID_30: 'o5p6q7r8-s9t0-1234-opqr-567890123456',
  ID_31: 'p6q7r8s9-t0u1-2345-pqrs-678901234567',
  ID_32: 'q7r8s9t0-u1v2-3456-qrst-789012345678',
  ID_33: 'r8s9t0u1-v2w3-4567-rstu-890123456789',
  ID_34: 's9t0u1v2-w3x4-5678-stuv-901234567890',
  ID_35: 't0u1v2w3-x4y5-6789-tuvw-012345678901',
};

export const MKT_COMBO_VARIANT_DATA_SEEDS: MktComboVariantDataSeed[] = [
  // Gaming Setup Combo (ID_1) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_1,
    name: 'Gaming Setup - Black Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_1,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_1,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_2,
    name: 'Gaming Setup - White LED Lamp',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_1,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_10,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Office Essentials Bundle (ID_2) - 3 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_3,
    name: 'Office Essentials - Black Mesh Chair',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_2,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_6,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_4,
    name: 'Office Essentials - White LED Lamp',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_2,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_10,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_5,
    name: 'Office Essentials - Silver Water Bottle',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_2,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_9,
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Coffee Lover Package (ID_3) - 3 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_6,
    name: 'Coffee Lover - Light Roast Beans',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_3,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_4,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_7,
    name: 'Coffee Lover - Dark Roast Beans',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_3,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_5,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_8,
    name: 'Coffee Lover - Silver Water Bottle',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_3,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_9,
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Premium Audio Setup (ID_4) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_9,
    name: 'Premium Audio - White Premium Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_4,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_2,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_10,
    name: 'Premium Audio - Black LED Lamp with Remote',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_4,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Executive Office Suite (ID_5) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_11,
    name: 'Executive Suite - Executive Chair',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_5,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_8,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_12,
    name: 'Executive Suite - Black LED Lamp with Remote',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_5,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Home Office Starter (ID_6) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_13,
    name: 'Home Office - Black Mesh Chair',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_6,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_6,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_14,
    name: 'Home Office - White LED Lamp',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_6,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_10,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Wellness & Productivity (ID_7) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_15,
    name: 'Wellness - Silver Water Bottle',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_7,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_9,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_16,
    name: 'Wellness - Light Roast Coffee',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_7,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_4,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Student Essentials (ID_8) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_17,
    name: 'Student - Black Standard Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_8,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_1,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_18,
    name: 'Student - White LED Lamp',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_8,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_10,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Creative Workspace (ID_9) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_19,
    name: 'Creative - Blue Limited Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_9,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_3,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_20,
    name: 'Creative - Black LED Lamp with Remote',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_9,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Remote Work Pro (ID_10) - 3 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_21,
    name: 'Remote Work - Gray Leather Chair',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_10,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_7,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_22,
    name: 'Remote Work - White Premium Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_10,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_2,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_23,
    name: 'Remote Work - Black LED Lamp with Remote',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_10,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Minimalist Setup (ID_11) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_24,
    name: 'Minimalist - Black Standard Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_11,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_1,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_25,
    name: 'Minimalist - Silver Water Bottle',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_11,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_9,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Luxury Office Collection (ID_12) - 3 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_26,
    name: 'Luxury - Executive Chair',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_12,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_8,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_27,
    name: 'Luxury - Blue Limited Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_12,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_3,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_28,
    name: 'Luxury - Black LED Lamp with Remote',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_12,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Budget-Friendly Bundle (ID_13) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_29,
    name: 'Budget - Black Standard Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_13,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_1,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_30,
    name: 'Budget - Light Roast Coffee',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_13,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_4,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Tech Enthusiast Pack (ID_14) - 2 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_31,
    name: 'Tech Enthusiast - Blue Limited Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_14,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_3,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_32,
    name: 'Tech Enthusiast - Black LED Lamp with Remote',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_14,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },

  // Complete Workspace Solution (ID_15) - 3 variants
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_33,
    name: 'Complete Workspace - Gray Leather Chair',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_15,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_7,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_34,
    name: 'Complete Workspace - White Premium Headphones',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_15,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_2,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
  {
    id: MKT_COMBO_VARIANT_DATA_SEEDS_IDS.ID_35,
    name: 'Complete Workspace - Black LED Lamp with Remote',
    quantity: 1,
    mktComboId: MKT_COMBO_DATA_SEEDS_IDS.ID_15,
    mktVariantId: MKT_VARIANT_DATA_SEEDS_IDS.ID_11,
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim A',
  },
];
