import {
  PERMISSION_ACTION_KEYS,
  PERMISSION_RISK_LEVELS,
} from 'src/mkt-core/mkt-permission-template/constants/permission-actions.constants';
import { PermissionActionSeed } from 'src/mkt-core/mkt-permission-template/types/permissions.type';
import { PERMISSION_ACTION_CATEGORY } from 'src/mkt-core/mkt-permission-template/constants/permission-template-options.constants';

type MktPermissionActionDataSeed = {
  id: string;
  actionKey: string;
  actionName: string;
  actionCategory: string;
  description: string;
  riskLevel: string;
  requiresApproval: boolean;
  isSystemAction: boolean;
  isActive: boolean;
  position?: number;
};

export const MKT_PERMISSION_ACTION_DATA_SEED_COLUMNS: (keyof MktPermissionActionDataSeed)[] =
  [
    'id',
    'actionKey',
    'actionName',
    'actionCategory',
    'description',
    'riskLevel',
    'requiresApproval',
    'isSystemAction',
    'isActive',
    'position',
  ];

// Pre-generated UUIDs for consistent seeding (expanded for Enterprise features)
export const PERMISSION_ACTION_IDS = {
  // Basic CRUD
  READ: '7cf5c2fd-7bba-4036-bb2b-a90d829db4a4',
  CREATE: 'f1bb3937-ddac-43dc-9e2f-1308ea1b04a2',
  UPDATE: 'd877057b-cd1d-4954-80da-c2a73a774c8a',
  DELETE: '5796b5b2-56de-40fa-9d15-ed13cfccc12c',

  // Advanced operations
  EXPORT: '11397e02-61d2-4c38-9799-d6787046d0e2',
  IMPORT: 'c991e6ac-cede-4631-9dc1-13766bdd8b77',
  SHARE: 'a29b11bd-c28d-43ea-aed1-0da0db1d258c',
  PUBLISH: '4b80da91-dd46-44bc-8327-4f5807c18e0c',
  ARCHIVE: '16dabbbd-850f-479b-bb52-45706f673503',
  RESTORE: '950b7a59-1704-4edc-a4b4-99cf9f0b3582',

  // Approval operations
  APPROVE: '4c07b8d0-25bd-4b34-9f3a-be496869a892',
  REJECT: '6fe13464-840f-4d5e-97a7-7d7de20117f2',
  ESCALATE: '7de8446c-118e-43fb-8088-9bb4940e70c7',

  // System operations
  CONFIGURE: '97ce80ce-5458-40f1-b257-20221b20a447',
  MONITOR: '1cd59971-44d7-4406-a50e-2586c0840a1d',
  AUDIT: 'c89d1f16-3c1a-4586-922c-cd26ed0058cd',

  // Bulk operations
  BULK_CREATE: 'f88ffb1d-fd73-4d7e-b9a3-401c4444aa7b',
  BULK_UPDATE: '4a12f369-14d7-4a7d-8e01-f23493210fbd',
  BULK_DELETE: 'df2a4bfb-6fc0-4302-a15f-f747d06e0bb7',
  BULK_EXPORT: 'f8a5a4ec-73a5-4e3f-b082-f220eb8b84b7',

  // Team Management operations (new for 11-level hierarchy)
  MANAGE_TEAM: 'f347fdba-134d-420e-a5ac-5128047c2ed3',
  ASSIGN_TASKS: 'd79e3e2d-9381-45b4-b9ba-21d3638ab266',
  VIEW_TEAM_REPORTS: '1e18997d-5112-4a4b-bfc1-8784a24b71f9',
  CONDUCT_REVIEWS: 'd91b6f2c-5e66-4bba-a1a4-b74c82eec75a',

  // Financial operations (new for hierarchy-based permissions)
  ACCESS_SALARY_DATA: 'd66112f7-26aa-4458-8165-a6df145eaf39',
  APPROVE_TRANSACTIONS: 'c77cd444-9775-4547-bab4-cf17db144b7f',
  VIEW_FINANCIAL_REPORTS: '1516a1e2-9baf-4854-a1cf-5f1c32c57e29',
  BUDGET_MANAGEMENT: 'e70d5ad4-104c-4bdd-84aa-a8b81246196a',

  // Sensitive data access (hierarchy-based)
  ACCESS_SENSITIVE_DATA: 'b66a2c4e-fee4-40ad-8660-6c787100f6c2',
  VIEW_CONFIDENTIAL_INFO: '4423b0bb-4af6-41b0-888c-76af6202082f',
  BYPASS_WORKFLOW_APPROVAL: 'e401c4ec-5ebf-47cc-9af6-5ff67c800480',

  // Customer Management operations (CRM-specific) - Valid UUID v4s
  ASSIGN_CUSTOMER: 'd7f3e4f3-faf4-4645-ba97-dd3593542155',
  TRANSFER_CUSTOMER: '7e506010-b62c-4a24-a4f0-f112f243ac95',
  MERGE_CUSTOMERS: '7a7ab2f9-0046-49d9-a5a7-897d267317c9',
  CONVERT_LEAD: 'f75e3a47-0a23-44a5-aa53-79539958b645',

  // Communication operations (CRM-specific) - Valid UUID v4s
  SEND_EMAIL: 'ce2d1d08-cbf4-4518-a380-30b2ac632ed1',
  MAKE_CALL: 'acce8e08-5ed8-4698-8130-a30aa134d73f',
  SEND_SMS: 'aa31d720-a14a-4c5f-aa2b-cedfc36b605a',
  SCHEDULE_MEETING: 'b73260c7-e743-48e4-ba73-a36ad72099b4',

  // Deal Management operations (CRM-specific) - Valid UUID v4s
  CLOSE_DEAL: '9e47a0f4-a46d-472e-89ab-00afdbc0ed2a',
  CHANGE_DEAL_STAGE: 'fb609dfd-5fb6-46d1-9726-2e6100710da9',
  APPROVE_DISCOUNT: '5254c516-7b4b-4518-9749-0d5192d492e9',

  // Reporting operations (CRM-specific) - Valid UUID v4s
  CREATE_REPORT: '16243afb-790d-438e-b06d-c7eafb39d4d1',
  SCHEDULE_REPORT: '1e3157a7-5a80-452b-a616-0ce82423511c',
  VIEW_DASHBOARD: '1e7800db-6544-4aee-9f9d-c114ffb90e71',
  EXPORT_ANALYTICS: '09f76a1b-02af-42b7-9b03-80c3c5e11443',

  // User Management operations (CRM-specific) - Valid UUID v4s
  MANAGE_USERS: '3ffb8a20-fa6d-4883-84ea-b353724c0940',
  ASSIGN_ROLES: 'c2298267-fcd6-4b4b-9f6d-505f61a381bc',
  RESET_PASSWORD: 'a7a6439f-9918-41d1-894e-45ca16f0b715',
  VIEW_USER_ACTIVITY: '21d2461f-01f1-46bd-aec8-0779cecaf767',

  // Automation operations (CRM-specific) - Valid UUID v4s
  CONFIGURE_INTEGRATION: 'e7bbe80b-6991-487a-9868-7ffca23b0478',
  CREATE_WORKFLOW: '56543c1f-d531-4974-be67-89193438d7a2',
  EXECUTE_API: '5a1d2d5e-dc9a-49db-b129-21430f470ef2',

  // Security & Compliance Operations (Enterprise) - Valid UUID v4s
  MANAGE_SECURITY_POLICIES: '039428ee-7635-409e-822a-3dbc779a65fa',
  CONFIGURE_ACCESS_CONTROLS: 'a076b33c-f9ae-4c0d-bd73-2590c172c089',
  VIEW_SECURITY_LOGS: 'bda12c60-03a0-4ecb-b36a-5b80d3463c88',
  CONDUCT_SECURITY_AUDIT: 'b5124fe0-2163-438c-8be7-2da15e86b1d6',
  MANAGE_COMPLIANCE_RULES: '1e85ad0f-5382-4b6d-bf13-1a9eb00b48ef',
  GENERATE_COMPLIANCE_REPORT: '8582c58f-3177-4216-8964-63286da3dac0',
  CLASSIFY_DATA: 'e2b28865-cca2-4ad5-b443-4d3e05446b10',
  MANAGE_DATA_RETENTION: '295d5dc9-ac5f-4b55-9525-7073e74e8abf',
  HANDLE_PRIVACY_REQUEST: '33cc2031-1403-4811-b36c-c60e6afd5a60',
  CONFIGURE_DATA_MASKING: '6fe9de14-120d-4223-a9dc-9bd8741ffbe0',

  // Integration & API Management (Enterprise) - Valid UUID v4s
  CREATE_API_KEY: 'd78d153d-8158-4dc3-857f-9b425507c48a',
  MANAGE_API_RATE_LIMITS: '718d4842-2c95-4ed2-9228-2b2671be7c89',
  CONFIGURE_OAUTH: '3c245a34-0066-4926-aa38-b04d048407b8',
  MANAGE_INTEGRATIONS: '365d8172-574e-4ca2-8208-4aaca7a53d20',
  CREATE_WEBHOOK: 'c6379b6c-45a0-4c5a-b91d-537967e62290',
  CONFIGURE_WEBHOOK: '1641764d-1af9-44c6-88ba-ad2900f961b8',
  ACCESS_THIRD_PARTY_SERVICE: '44d1ed2d-885e-46c7-9574-777349983e8f',
  MANAGE_SERVICE_CONNECTIONS: '0339acff-053d-42fa-8276-042b6cc2c0ae',

  // Advanced Enterprise Features - Valid UUID v4s
  CREATE_COMPLEX_WORKFLOW: '52ac06d7-eb25-4acc-a7b5-c536d3279629',
  ORCHESTRATE_PROCESSES: '6d9b543a-8eb9-4a65-b124-5f86e150035c',
  CREATE_BI_DASHBOARD: '37663498-7505-4552-8140-041128e14ed3',
  ACCESS_BI_TOOLS: 'c763235b-26bd-410b-ac75-775e3e90d07f',
  PERFORM_ADVANCED_ANALYTICS: '11a8c126-c978-4974-b7ef-ae42c2472d39',
  CREATE_PREDICTIVE_MODEL: '9b2538d2-c6d4-4450-96cd-1ba03498ae42',
  CREATE_CUSTOM_FIELDS: '77daa7e1-db4c-4aee-9a21-fef5ed01e126',
  DEVELOP_CUSTOM_APPS: '3da5112a-aac6-49cb-a816-0c5860b1bdfd',
  MANAGE_TENANTS: '4eda890b-f133-4e18-ac5f-9c69aaf00674',
  CONFIGURE_MULTI_TENANCY: '2e656cc8-5d0d-48e0-ab7f-d75b72bbee18',

  // Operational Excellence (Enterprise) - Valid UUID v4s
  CONFIGURE_MONITORING: '7a7f901a-aa52-40f9-a301-72aa4e36df10',
  VIEW_SYSTEM_METRICS: '656c8a19-1133-4566-a86a-b4342133c103',
  MANAGE_ALERTS: '3cc5402f-c132-42c2-83da-265bffed1947',
  BACKUP_DATA: 'a72b6fd5-25e9-4190-9fc7-eac97754d059',
  RESTORE_BACKUP: '1b1f065b-0620-4512-973c-6a1819ce0244',
  CONFIGURE_DISASTER_RECOVERY: '14762606-7b20-40df-a445-6f00f0746994',
  OPTIMIZE_PERFORMANCE: 'f0fdcfef-74f9-43b8-b5cd-25d4b9da9ebd',
  TUNE_DATABASE: '148c1454-bf9c-49ef-95fd-20a8f4fc3d67',
  PLAN_CAPACITY: '2bf4ba9e-2bce-4f2d-a168-426156f5ccdb',
  MANAGE_RESOURCES: '37b5a0a8-00c9-4eb5-8ef1-f0e7a8a9fee5',

  // Data & Content Management (Enterprise) - Valid UUID v4s
  MIGRATE_DATA: '29737101-347d-437e-9fb4-9c096c31bcac',
  TRANSFORM_DATA: '2f86c719-b6e8-4e95-9b52-f597e4355ae5',
  MANAGE_CONTENT_LIFECYCLE: '3745f9d0-88d0-483c-9a65-cb01f5776d38',
  PUBLISH_CONTENT: '7089b7a2-3848-4ec8-952c-fcb046aebbbd',
  MANAGE_DOCUMENTS: '5d0268c2-5023-4808-8917-652e97d846b4',
  VERSION_CONTROL_DOCUMENTS: '7798530f-8d4f-463d-be34-15bca3a4c0cb',
  MANAGE_KNOWLEDGE_BASE: '9010cb05-df99-4dd3-90a8-6f2fd3f81d95',
  CURATE_KNOWLEDGE: '00c8229b-0cd9-4771-bcf4-266048a85c95',

  // Advanced CRM & Sales Operations (Enterprise) - Valid UUID v4s
  MANAGE_TERRITORIES: '683302b6-f769-453b-996d-7e83bb1c62c2',
  ASSIGN_TERRITORIES: 'f37833a3-242d-48c5-af69-5e61f6d5b883',
  SET_QUOTAS: '5b2fbb34-c975-4b7b-9540-94834465206a',
  TRACK_QUOTA_PERFORMANCE: 'd6d1cd9b-0138-43dc-bd70-9b183c27e584',
  CALCULATE_COMMISSION: 'd852c241-905c-4035-93fc-b8e5ffdece79',
  APPROVE_COMMISSION: '31901f78-a716-4d1a-9ef7-84bf3789f2c8',
  CREATE_FORECAST: 'c60353a1-28a1-4d4e-bea0-9edbb6813a44',
  ANALYZE_FORECAST: '86c7ecad-b6a5-4b84-97fc-d1379cd23785',

  // Multi-level Approval Workflows (Enterprise) - Valid UUID v4s
  CREATE_APPROVAL_CHAIN: '25351b45-5dbd-4d79-bb07-893fd1bccf6e',
  CONFIGURE_APPROVAL_RULES: '95431f8b-f042-496f-84a9-633de13ae226',
  MANAGE_ESCALATION_RULES: '82754166-8607-4034-b083-9a7206812a4c',
  HANDLE_ESCALATION: 'b5e944b6-57c4-47df-9db4-8a12a295b373',
  DELEGATE_PERMISSIONS: '8671c676-a74d-4721-aaff-337b30d100a5',
  MANAGE_DELEGATION: '773d1cda-ee72-496e-9ecd-1380d4487030',
} as const;

// Permission Actions Seed Data
const PERMISSION_ACTIONS_SEED: PermissionActionSeed[] = [
  // Basic CRUD Operations
  {
    id: PERMISSION_ACTION_IDS.READ,
    actionKey: PERMISSION_ACTION_KEYS.READ,
    actionName: 'Read',
    actionCategory: PERMISSION_ACTION_CATEGORY.BASIC_CRUD,
    description: 'Xem và đọc dữ liệu không có chỉnh sửa',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CREATE,
    actionKey: PERMISSION_ACTION_KEYS.CREATE,
    actionName: 'Create',
    actionCategory: PERMISSION_ACTION_CATEGORY.BASIC_CRUD,
    description: 'Tạo mới bản ghi và dữ liệu',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.UPDATE,
    actionKey: PERMISSION_ACTION_KEYS.UPDATE,
    actionName: 'Update',
    actionCategory: PERMISSION_ACTION_CATEGORY.BASIC_CRUD,
    description: 'Chỉnh sửa và cập nhật bản ghi hiện có',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.DELETE,
    actionKey: PERMISSION_ACTION_KEYS.DELETE,
    actionName: 'Delete',
    actionCategory: PERMISSION_ACTION_CATEGORY.BASIC_CRUD,
    description: 'Xóa bản ghi vĩnh viễn hoặc xóa mềm',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Advanced Operations
  {
    id: PERMISSION_ACTION_IDS.EXPORT,
    actionKey: PERMISSION_ACTION_KEYS.EXPORT,
    actionName: 'Export',
    actionCategory: PERMISSION_ACTION_CATEGORY.ADVANCED,
    description: 'Xuất dữ liệu ra định dạng bên ngoài (CSV, PDF, v.v.)',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.IMPORT,
    actionKey: PERMISSION_ACTION_KEYS.IMPORT,
    actionName: 'Import',
    actionCategory: PERMISSION_ACTION_CATEGORY.ADVANCED,
    description: 'Nhập dữ liệu từ nguồn bên ngoài',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.SHARE,
    actionKey: PERMISSION_ACTION_KEYS.SHARE,
    actionName: 'Share',
    actionCategory: PERMISSION_ACTION_CATEGORY.ADVANCED,
    description: 'Chia sẻ bản ghi với người dùng khác hoặc bên ngoài',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.PUBLISH,
    actionKey: PERMISSION_ACTION_KEYS.PUBLISH,
    actionName: 'Publish',
    actionCategory: PERMISSION_ACTION_CATEGORY.ADVANCED,
    description: 'Xuất bản nội dung hoặc bản ghi để truy cập công khai',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ARCHIVE,
    actionKey: PERMISSION_ACTION_KEYS.ARCHIVE,
    actionName: 'Archive',
    actionCategory: PERMISSION_ACTION_CATEGORY.ADVANCED,
    description: 'Lưu trữ bản ghi dài hạn',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.RESTORE,
    actionKey: PERMISSION_ACTION_KEYS.RESTORE,
    actionName: 'Restore',
    actionCategory: PERMISSION_ACTION_CATEGORY.ADVANCED,
    description: 'Khôi phục bản ghi đã lưu trữ hoặc đã xóa',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Approval Operations
  {
    id: PERMISSION_ACTION_IDS.APPROVE,
    actionKey: PERMISSION_ACTION_KEYS.APPROVE,
    actionName: 'Approve',
    actionCategory: PERMISSION_ACTION_CATEGORY.APPROVAL,
    description: 'Phê duyệt các hành động hoặc yêu cầu đang chờ',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.REJECT,
    actionKey: PERMISSION_ACTION_KEYS.REJECT,
    actionName: 'Reject',
    actionCategory: PERMISSION_ACTION_CATEGORY.APPROVAL,
    description: 'Từ chối các hành động hoặc yêu cầu đang chờ',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ESCALATE,
    actionKey: PERMISSION_ACTION_KEYS.ESCALATE,
    actionName: 'Escalate',
    actionCategory: PERMISSION_ACTION_CATEGORY.APPROVAL,
    description: 'Chuyển yêu cầu lên cấp cao hơn',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // System Operations
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE,
    actionName: 'Configure',
    actionCategory: PERMISSION_ACTION_CATEGORY.SYSTEM,
    description: 'Cấu hình các thiết lập và tham số hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MONITOR,
    actionKey: PERMISSION_ACTION_KEYS.MONITOR,
    actionName: 'Monitor',
    actionCategory: PERMISSION_ACTION_CATEGORY.SYSTEM,
    description: 'Giám sát hiệu suất hệ thống và hoạt động người dùng',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.AUDIT,
    actionKey: PERMISSION_ACTION_KEYS.AUDIT,
    actionName: 'Audit',
    actionCategory: PERMISSION_ACTION_CATEGORY.SYSTEM,
    description: 'Truy cập nhật ký kiểm toán và thông tin bảo mật',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // Bulk Operations
  {
    id: PERMISSION_ACTION_IDS.BULK_CREATE,
    actionKey: PERMISSION_ACTION_KEYS.BULK_CREATE,
    actionName: 'Bulk Create',
    actionCategory: PERMISSION_ACTION_CATEGORY.BULK_OPERATIONS,
    description: 'Tạo nhiều bản ghi trong thao tác hàng loạt',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.BULK_UPDATE,
    actionKey: PERMISSION_ACTION_KEYS.BULK_UPDATE,
    actionName: 'Bulk Update',
    actionCategory: PERMISSION_ACTION_CATEGORY.BULK_OPERATIONS,
    description: 'Cập nhật nhiều bản ghi trong thao tác hàng loạt',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.BULK_DELETE,
    actionKey: PERMISSION_ACTION_KEYS.BULK_DELETE,
    actionName: 'Bulk Delete',
    actionCategory: PERMISSION_ACTION_CATEGORY.BULK_OPERATIONS,
    description: 'Xóa nhiều bản ghi trong thao tác hàng loạt',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.BULK_EXPORT,
    actionKey: PERMISSION_ACTION_KEYS.BULK_EXPORT,
    actionName: 'Bulk Export',
    actionCategory: PERMISSION_ACTION_CATEGORY.BULK_OPERATIONS,
    description: 'Xuất tập dữ liệu lớn trong thao tác hàng loạt',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Team Management Operations (for 11-level hierarchy)
  {
    id: PERMISSION_ACTION_IDS.MANAGE_TEAM,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_TEAM,
    actionName: 'Manage Team',
    actionCategory: PERMISSION_ACTION_CATEGORY.TEAM_MANAGEMENT,
    description: 'Quản lý thành viên nhóm, phân công vai trò và trách nhiệm',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ASSIGN_TASKS,
    actionKey: PERMISSION_ACTION_KEYS.ASSIGN_TASKS,
    actionName: 'Assign Tasks',
    actionCategory: PERMISSION_ACTION_CATEGORY.TEAM_MANAGEMENT,
    description: 'Phân công nhiệm vụ và dự án cho thành viên nhóm',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VIEW_TEAM_REPORTS,
    actionKey: PERMISSION_ACTION_KEYS.VIEW_TEAM_REPORTS,
    actionName: 'View Team Reports',
    actionCategory: PERMISSION_ACTION_CATEGORY.TEAM_MANAGEMENT,
    description: 'Xem báo cáo hiệu suất nhóm và phân tích',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONDUCT_REVIEWS,
    actionKey: PERMISSION_ACTION_KEYS.CONDUCT_REVIEWS,
    actionName: 'Conduct Reviews',
    actionCategory: PERMISSION_ACTION_CATEGORY.TEAM_MANAGEMENT,
    description: 'Tiến hành đánh giá hiệu suất và đánh giá nhân viên',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // Financial Operations (for higher hierarchy levels)
  {
    id: PERMISSION_ACTION_IDS.ACCESS_SALARY_DATA,
    actionKey: PERMISSION_ACTION_KEYS.ACCESS_SALARY_DATA,
    actionName: 'Access Salary Data',
    actionCategory: PERMISSION_ACTION_CATEGORY.FINANCIAL,
    description: 'Truy cập thông tin lương và thù lao',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.APPROVE_TRANSACTIONS,
    actionKey: PERMISSION_ACTION_KEYS.APPROVE_TRANSACTIONS,
    actionName: 'Approve Transactions',
    actionCategory: PERMISSION_ACTION_CATEGORY.FINANCIAL,
    description: 'Phê duyệt các giao dịch tài chính và chi phí',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VIEW_FINANCIAL_REPORTS,
    actionKey: PERMISSION_ACTION_KEYS.VIEW_FINANCIAL_REPORTS,
    actionName: 'View Financial Reports',
    actionCategory: PERMISSION_ACTION_CATEGORY.FINANCIAL,
    description: 'Xem báo cáo tài chính và thông tin ngân sách',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.BUDGET_MANAGEMENT,
    actionKey: PERMISSION_ACTION_KEYS.BUDGET_MANAGEMENT,
    actionName: 'Budget Management',
    actionCategory: PERMISSION_ACTION_CATEGORY.FINANCIAL,
    description: 'Quản lý ngân sách phòng ban và dự án',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Sensitive Data Access (hierarchy-based permissions)
  {
    id: PERMISSION_ACTION_IDS.ACCESS_SENSITIVE_DATA,
    actionKey: PERMISSION_ACTION_KEYS.ACCESS_SENSITIVE_DATA,
    actionName: 'Access Sensitive Data',
    actionCategory: PERMISSION_ACTION_CATEGORY.SYSTEM,
    description: 'Truy cập dữ liệu nhạy cảm và mật của doanh nghiệp',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VIEW_CONFIDENTIAL_INFO,
    actionKey: PERMISSION_ACTION_KEYS.VIEW_CONFIDENTIAL_INFO,
    actionName: 'View Confidential Info',
    actionCategory: PERMISSION_ACTION_CATEGORY.SYSTEM,
    description: 'Xem thông tin và tài liệu bảo mật',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.BYPASS_WORKFLOW_APPROVAL,
    actionKey: PERMISSION_ACTION_KEYS.BYPASS_WORKFLOW_APPROVAL,
    actionName: 'Bypass Workflow Approval',
    actionCategory: PERMISSION_ACTION_CATEGORY.SYSTEM,
    description: 'Bỏ qua quy trình phê duyệt tiêu chuẩn',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Customer Management Operations (CRM-specific)
  {
    id: PERMISSION_ACTION_IDS.ASSIGN_CUSTOMER,
    actionKey: PERMISSION_ACTION_KEYS.ASSIGN_CUSTOMER,
    actionName: 'Assign Customer',
    actionCategory: PERMISSION_ACTION_CATEGORY.CUSTOMER_MANAGEMENT,
    description: 'Phân công khách hàng cho nhân viên kinh doanh',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.TRANSFER_CUSTOMER,
    actionKey: PERMISSION_ACTION_KEYS.TRANSFER_CUSTOMER,
    actionName: 'Transfer Customer',
    actionCategory: PERMISSION_ACTION_CATEGORY.CUSTOMER_MANAGEMENT,
    description: 'Chuyển quyền sở hữu khách hàng cho người dùng khác',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MERGE_CUSTOMERS,
    actionKey: PERMISSION_ACTION_KEYS.MERGE_CUSTOMERS,
    actionName: 'Merge Customers',
    actionCategory: PERMISSION_ACTION_CATEGORY.CUSTOMER_MANAGEMENT,
    description: 'Gộp các bản ghi khách hàng trùng lặp',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONVERT_LEAD,
    actionKey: PERMISSION_ACTION_KEYS.CONVERT_LEAD,
    actionName: 'Convert Lead',
    actionCategory: PERMISSION_ACTION_CATEGORY.CUSTOMER_MANAGEMENT,
    description: 'Chuyển đổi khách hàng tiềm năng thành khách hàng',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // Communication Operations (CRM-specific)
  {
    id: PERMISSION_ACTION_IDS.SEND_EMAIL,
    actionKey: PERMISSION_ACTION_KEYS.SEND_EMAIL,
    actionName: 'Send Email',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMMUNICATION,
    description: 'Gửi email cho khách hàng',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MAKE_CALL,
    actionKey: PERMISSION_ACTION_KEYS.MAKE_CALL,
    actionName: 'Make Call',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMMUNICATION,
    description: 'Gọi điện thoại cho khách hàng',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.SEND_SMS,
    actionKey: PERMISSION_ACTION_KEYS.SEND_SMS,
    actionName: 'Send SMS',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMMUNICATION,
    description: 'Gửi tin nhắn SMS cho khách hàng',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.SCHEDULE_MEETING,
    actionKey: PERMISSION_ACTION_KEYS.SCHEDULE_MEETING,
    actionName: 'Schedule Meeting',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMMUNICATION,
    description: 'Lên lịch cuộc họp với khách hàng',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // Deal Management Operations (CRM-specific)
  {
    id: PERMISSION_ACTION_IDS.CLOSE_DEAL,
    actionKey: PERMISSION_ACTION_KEYS.CLOSE_DEAL,
    actionName: 'Close Deal',
    actionCategory: PERMISSION_ACTION_CATEGORY.DEAL_MANAGEMENT,
    description: 'Đánh dấu giao dịch là thành công hoặc thất bại',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CHANGE_DEAL_STAGE,
    actionKey: PERMISSION_ACTION_KEYS.CHANGE_DEAL_STAGE,
    actionName: 'Change Deal Stage',
    actionCategory: PERMISSION_ACTION_CATEGORY.DEAL_MANAGEMENT,
    description: 'Di chuyển giao dịch qua các giai đoạn pipeline',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.APPROVE_DISCOUNT,
    actionKey: PERMISSION_ACTION_KEYS.APPROVE_DISCOUNT,
    actionName: 'Approve Discount',
    actionCategory: PERMISSION_ACTION_CATEGORY.DEAL_MANAGEMENT,
    description: 'Phê duyệt chiết khấu đặc biệt cho giao dịch',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Reporting Operations (CRM-specific)
  {
    id: PERMISSION_ACTION_IDS.CREATE_REPORT,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_REPORT,
    actionName: 'Create Report',
    actionCategory: PERMISSION_ACTION_CATEGORY.REPORTING,
    description: 'Tạo báo cáo tùy chỉnh',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.SCHEDULE_REPORT,
    actionKey: PERMISSION_ACTION_KEYS.SCHEDULE_REPORT,
    actionName: 'Schedule Report',
    actionCategory: PERMISSION_ACTION_CATEGORY.REPORTING,
    description: 'Lên lịch báo cáo tự động',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VIEW_DASHBOARD,
    actionKey: PERMISSION_ACTION_KEYS.VIEW_DASHBOARD,
    actionName: 'View Dashboard',
    actionCategory: PERMISSION_ACTION_CATEGORY.REPORTING,
    description: 'Xem bảng điều khiển phân tích',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.EXPORT_ANALYTICS,
    actionKey: PERMISSION_ACTION_KEYS.EXPORT_ANALYTICS,
    actionName: 'Export Analytics',
    actionCategory: PERMISSION_ACTION_CATEGORY.REPORTING,
    description: 'Xuất dữ liệu phân tích',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // User Management Operations (CRM-specific)
  {
    id: PERMISSION_ACTION_IDS.MANAGE_USERS,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_USERS,
    actionName: 'Manage Users',
    actionCategory: PERMISSION_ACTION_CATEGORY.USER_MANAGEMENT,
    description: 'Tạo và chỉnh sửa tài khoản người dùng',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ASSIGN_ROLES,
    actionKey: PERMISSION_ACTION_KEYS.ASSIGN_ROLES,
    actionName: 'Assign Roles',
    actionCategory: PERMISSION_ACTION_CATEGORY.USER_MANAGEMENT,
    description: 'Gán vai trò và quyền hạn cho người dùng',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.RESET_PASSWORD,
    actionKey: PERMISSION_ACTION_KEYS.RESET_PASSWORD,
    actionName: 'Reset Password',
    actionCategory: PERMISSION_ACTION_CATEGORY.USER_MANAGEMENT,
    description: 'Đặt lại mật khẩu người dùng',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VIEW_USER_ACTIVITY,
    actionKey: PERMISSION_ACTION_KEYS.VIEW_USER_ACTIVITY,
    actionName: 'View User Activity',
    actionCategory: PERMISSION_ACTION_CATEGORY.USER_MANAGEMENT,
    description: 'Xem nhật ký hoạt động người dùng',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // Automation Operations (CRM-specific)
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_INTEGRATION,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_INTEGRATION,
    actionName: 'Configure Integration',
    actionCategory: PERMISSION_ACTION_CATEGORY.AUTOMATION,
    description: 'Thiết lập tích hợp với bên thứ ba',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CREATE_WORKFLOW,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_WORKFLOW,
    actionName: 'Create Workflow',
    actionCategory: PERMISSION_ACTION_CATEGORY.AUTOMATION,
    description: 'Tạo quy trình tự động hóa',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.EXECUTE_API,
    actionKey: PERMISSION_ACTION_KEYS.EXECUTE_API,
    actionName: 'Execute API',
    actionCategory: PERMISSION_ACTION_CATEGORY.AUTOMATION,
    description: 'Thực thi các API và tích hợp',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Security & Compliance Operations (Enterprise)
  {
    id: PERMISSION_ACTION_IDS.MANAGE_SECURITY_POLICIES,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_SECURITY_POLICIES,
    actionName: 'Manage Security Policies',
    actionCategory: PERMISSION_ACTION_CATEGORY.SECURITY_OPERATIONS,
    description: 'Quản lý chính sách bảo mật hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_ACCESS_CONTROLS,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_ACCESS_CONTROLS,
    actionName: 'Configure Access Controls',
    actionCategory: PERMISSION_ACTION_CATEGORY.SECURITY_OPERATIONS,
    description: 'Cấu hình kiểm soát truy cập và quyền hạn',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VIEW_SECURITY_LOGS,
    actionKey: PERMISSION_ACTION_KEYS.VIEW_SECURITY_LOGS,
    actionName: 'View Security Logs',
    actionCategory: PERMISSION_ACTION_CATEGORY.SECURITY_OPERATIONS,
    description: 'Xem nhật ký bảo mật và hoạt động đáng nghi',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONDUCT_SECURITY_AUDIT,
    actionKey: PERMISSION_ACTION_KEYS.CONDUCT_SECURITY_AUDIT,
    actionName: 'Conduct Security Audit',
    actionCategory: PERMISSION_ACTION_CATEGORY.AUDIT_OPERATIONS,
    description: 'Tiến hành kiểm toán bảo mật hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_COMPLIANCE_RULES,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_COMPLIANCE_RULES,
    actionName: 'Manage Compliance Rules',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMPLIANCE_OPERATIONS,
    description: 'Quản lý quy tắc tuân thủ (GDPR, SOX, etc.)',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.GENERATE_COMPLIANCE_REPORT,
    actionKey: PERMISSION_ACTION_KEYS.GENERATE_COMPLIANCE_REPORT,
    actionName: 'Generate Compliance Report',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMPLIANCE_OPERATIONS,
    description: 'Tạo báo cáo tuân thủ quy định',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CLASSIFY_DATA,
    actionKey: PERMISSION_ACTION_KEYS.CLASSIFY_DATA,
    actionName: 'Classify Data',
    actionCategory: PERMISSION_ACTION_CATEGORY.DATA_GOVERNANCE,
    description: 'Phân loại dữ liệu theo mức độ nhạy cảm',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_DATA_RETENTION,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_DATA_RETENTION,
    actionName: 'Manage Data Retention',
    actionCategory: PERMISSION_ACTION_CATEGORY.DATA_GOVERNANCE,
    description: 'Quản lý chính sách lưu trữ dữ liệu',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.HANDLE_PRIVACY_REQUEST,
    actionKey: PERMISSION_ACTION_KEYS.HANDLE_PRIVACY_REQUEST,
    actionName: 'Handle Privacy Request',
    actionCategory: PERMISSION_ACTION_CATEGORY.PRIVACY_OPERATIONS,
    description: 'Xử lý yêu cầu quyền riêng tư (GDPR)',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_DATA_MASKING,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_DATA_MASKING,
    actionName: 'Configure Data Masking',
    actionCategory: PERMISSION_ACTION_CATEGORY.PRIVACY_OPERATIONS,
    description: 'Cấu hình che giấu dữ liệu nhạy cảm',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Integration & API Management (Enterprise)
  {
    id: PERMISSION_ACTION_IDS.CREATE_API_KEY,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_API_KEY,
    actionName: 'Create API Key',
    actionCategory: PERMISSION_ACTION_CATEGORY.API_MANAGEMENT,
    description: 'Tạo khóa API cho tích hợp bên ngoài',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_API_RATE_LIMITS,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_API_RATE_LIMITS,
    actionName: 'Manage API Rate Limits',
    actionCategory: PERMISSION_ACTION_CATEGORY.API_MANAGEMENT,
    description: 'Quản lý giới hạn tần suất API',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_OAUTH,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_OAUTH,
    actionName: 'Configure OAuth',
    actionCategory: PERMISSION_ACTION_CATEGORY.API_MANAGEMENT,
    description: 'Cấu hình OAuth và xác thực API',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_INTEGRATIONS,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_INTEGRATIONS,
    actionName: 'Manage Integrations',
    actionCategory: PERMISSION_ACTION_CATEGORY.INTEGRATION_OPERATIONS,
    description: 'Quản lý các tích hợp bên thứ ba',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CREATE_WEBHOOK,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_WEBHOOK,
    actionName: 'Create Webhook',
    actionCategory: PERMISSION_ACTION_CATEGORY.WEBHOOK_MANAGEMENT,
    description: 'Tạo webhook cho thông báo tự động',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_WEBHOOK,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_WEBHOOK,
    actionName: 'Configure Webhook',
    actionCategory: PERMISSION_ACTION_CATEGORY.WEBHOOK_MANAGEMENT,
    description: 'Cấu hình webhook và endpoint',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ACCESS_THIRD_PARTY_SERVICE,
    actionKey: PERMISSION_ACTION_KEYS.ACCESS_THIRD_PARTY_SERVICE,
    actionName: 'Access Third Party Service',
    actionCategory: PERMISSION_ACTION_CATEGORY.THIRD_PARTY_SERVICES,
    description: 'Truy cập dịch vụ bên thứ ba',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_SERVICE_CONNECTIONS,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_SERVICE_CONNECTIONS,
    actionName: 'Manage Service Connections',
    actionCategory: PERMISSION_ACTION_CATEGORY.THIRD_PARTY_SERVICES,
    description: 'Quản lý kết nối với dịch vụ bên ngoài',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Advanced Enterprise Features
  {
    id: PERMISSION_ACTION_IDS.CREATE_COMPLEX_WORKFLOW,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_COMPLEX_WORKFLOW,
    actionName: 'Create Complex Workflow',
    actionCategory: PERMISSION_ACTION_CATEGORY.WORKFLOW_ORCHESTRATION,
    description: 'Tạo quy trình phức tạp đa bước',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ORCHESTRATE_PROCESSES,
    actionKey: PERMISSION_ACTION_KEYS.ORCHESTRATE_PROCESSES,
    actionName: 'Orchestrate Processes',
    actionCategory: PERMISSION_ACTION_CATEGORY.WORKFLOW_ORCHESTRATION,
    description: 'Điều phối các quy trình nghiệp vụ',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CREATE_BI_DASHBOARD,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_BI_DASHBOARD,
    actionName: 'Create BI Dashboard',
    actionCategory: PERMISSION_ACTION_CATEGORY.BUSINESS_INTELLIGENCE,
    description: 'Tạo dashboard business intelligence',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ACCESS_BI_TOOLS,
    actionKey: PERMISSION_ACTION_KEYS.ACCESS_BI_TOOLS,
    actionName: 'Access BI Tools',
    actionCategory: PERMISSION_ACTION_CATEGORY.BUSINESS_INTELLIGENCE,
    description: 'Truy cập công cụ business intelligence',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.PERFORM_ADVANCED_ANALYTICS,
    actionKey: PERMISSION_ACTION_KEYS.PERFORM_ADVANCED_ANALYTICS,
    actionName: 'Perform Advanced Analytics',
    actionCategory: PERMISSION_ACTION_CATEGORY.ANALYTICS_OPERATIONS,
    description: 'Thực hiện phân tích dữ liệu nâng cao',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CREATE_PREDICTIVE_MODEL,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_PREDICTIVE_MODEL,
    actionName: 'Create Predictive Model',
    actionCategory: PERMISSION_ACTION_CATEGORY.ANALYTICS_OPERATIONS,
    description: 'Tạo mô hình dự đoán và machine learning',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CREATE_CUSTOM_FIELDS,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_CUSTOM_FIELDS,
    actionName: 'Create Custom Fields',
    actionCategory: PERMISSION_ACTION_CATEGORY.CUSTOM_DEVELOPMENT,
    description: 'Tạo trường tùy chỉnh trong hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.DEVELOP_CUSTOM_APPS,
    actionKey: PERMISSION_ACTION_KEYS.DEVELOP_CUSTOM_APPS,
    actionName: 'Develop Custom Apps',
    actionCategory: PERMISSION_ACTION_CATEGORY.CUSTOM_DEVELOPMENT,
    description: 'Phát triển ứng dụng tùy chỉnh',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_TENANTS,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_TENANTS,
    actionName: 'Manage Tenants',
    actionCategory: PERMISSION_ACTION_CATEGORY.TENANT_MANAGEMENT,
    description: 'Quản lý các tenant trong hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_MULTI_TENANCY,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_MULTI_TENANCY,
    actionName: 'Configure Multi-Tenancy',
    actionCategory: PERMISSION_ACTION_CATEGORY.TENANT_MANAGEMENT,
    description: 'Cấu hình multi-tenancy architecture',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Operational Excellence (Enterprise)
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_MONITORING,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_MONITORING,
    actionName: 'Configure Monitoring',
    actionCategory: PERMISSION_ACTION_CATEGORY.MONITORING_OPERATIONS,
    description: 'Cấu hình giám sát hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VIEW_SYSTEM_METRICS,
    actionKey: PERMISSION_ACTION_KEYS.VIEW_SYSTEM_METRICS,
    actionName: 'View System Metrics',
    actionCategory: PERMISSION_ACTION_CATEGORY.MONITORING_OPERATIONS,
    description: 'Xem các chỉ số hiệu suất hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_ALERTS,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_ALERTS,
    actionName: 'Manage Alerts',
    actionCategory: PERMISSION_ACTION_CATEGORY.MONITORING_OPERATIONS,
    description: 'Quản lý cảnh báo và thông báo hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.BACKUP_DATA,
    actionKey: PERMISSION_ACTION_KEYS.BACKUP_DATA,
    actionName: 'Backup Data',
    actionCategory: PERMISSION_ACTION_CATEGORY.BACKUP_RECOVERY,
    description: 'Sao lưu dữ liệu hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.RESTORE_BACKUP,
    actionKey: PERMISSION_ACTION_KEYS.RESTORE_BACKUP,
    actionName: 'Restore Backup',
    actionCategory: PERMISSION_ACTION_CATEGORY.BACKUP_RECOVERY,
    description: 'Khôi phục từ bản sao lưu',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_DISASTER_RECOVERY,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_DISASTER_RECOVERY,
    actionName: 'Configure Disaster Recovery',
    actionCategory: PERMISSION_ACTION_CATEGORY.BACKUP_RECOVERY,
    description: 'Cấu hình khôi phục sau thảm họa',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.OPTIMIZE_PERFORMANCE,
    actionKey: PERMISSION_ACTION_KEYS.OPTIMIZE_PERFORMANCE,
    actionName: 'Optimize Performance',
    actionCategory: PERMISSION_ACTION_CATEGORY.PERFORMANCE_TUNING,
    description: 'Tối ưu hóa hiệu suất hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.TUNE_DATABASE,
    actionKey: PERMISSION_ACTION_KEYS.TUNE_DATABASE,
    actionName: 'Tune Database',
    actionCategory: PERMISSION_ACTION_CATEGORY.PERFORMANCE_TUNING,
    description: 'Tinh chỉnh hiệu suất database',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.PLAN_CAPACITY,
    actionKey: PERMISSION_ACTION_KEYS.PLAN_CAPACITY,
    actionName: 'Plan Capacity',
    actionCategory: PERMISSION_ACTION_CATEGORY.CAPACITY_MANAGEMENT,
    description: 'Lập kế hoạch công suất hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_RESOURCES,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_RESOURCES,
    actionName: 'Manage Resources',
    actionCategory: PERMISSION_ACTION_CATEGORY.CAPACITY_MANAGEMENT,
    description: 'Quản lý tài nguyên hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },

  // Data & Content Management (Enterprise)
  {
    id: PERMISSION_ACTION_IDS.MIGRATE_DATA,
    actionKey: PERMISSION_ACTION_KEYS.MIGRATE_DATA,
    actionName: 'Migrate Data',
    actionCategory: PERMISSION_ACTION_CATEGORY.DATA_MIGRATION,
    description: 'Di chuyển dữ liệu giữa các hệ thống',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.TRANSFORM_DATA,
    actionKey: PERMISSION_ACTION_KEYS.TRANSFORM_DATA,
    actionName: 'Transform Data',
    actionCategory: PERMISSION_ACTION_CATEGORY.DATA_MIGRATION,
    description: 'Biến đổi và làm sạch dữ liệu',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_CONTENT_LIFECYCLE,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_CONTENT_LIFECYCLE,
    actionName: 'Manage Content Lifecycle',
    actionCategory: PERMISSION_ACTION_CATEGORY.CONTENT_MANAGEMENT,
    description: 'Quản lý vòng đời nội dung',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.PUBLISH_CONTENT,
    actionKey: PERMISSION_ACTION_KEYS.PUBLISH_CONTENT,
    actionName: 'Publish Content',
    actionCategory: PERMISSION_ACTION_CATEGORY.CONTENT_MANAGEMENT,
    description: 'Xuất bản nội dung công khai',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_DOCUMENTS,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_DOCUMENTS,
    actionName: 'Manage Documents',
    actionCategory: PERMISSION_ACTION_CATEGORY.DOCUMENT_OPERATIONS,
    description: 'Quản lý tài liệu và file đính kèm',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.VERSION_CONTROL_DOCUMENTS,
    actionKey: PERMISSION_ACTION_KEYS.VERSION_CONTROL_DOCUMENTS,
    actionName: 'Version Control Documents',
    actionCategory: PERMISSION_ACTION_CATEGORY.DOCUMENT_OPERATIONS,
    description: 'Kiểm soát phiên bản tài liệu',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_KNOWLEDGE_BASE,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_KNOWLEDGE_BASE,
    actionName: 'Manage Knowledge Base',
    actionCategory: PERMISSION_ACTION_CATEGORY.KNOWLEDGE_MANAGEMENT,
    description: 'Quản lý cơ sở tri thức',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CURATE_KNOWLEDGE,
    actionKey: PERMISSION_ACTION_KEYS.CURATE_KNOWLEDGE,
    actionName: 'Curate Knowledge',
    actionCategory: PERMISSION_ACTION_CATEGORY.KNOWLEDGE_MANAGEMENT,
    description: 'Tuyển chọn và tổ chức tri thức',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // Advanced CRM & Sales Operations (Enterprise)
  {
    id: PERMISSION_ACTION_IDS.MANAGE_TERRITORIES,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_TERRITORIES,
    actionName: 'Manage Territories',
    actionCategory: PERMISSION_ACTION_CATEGORY.TERRITORY_MANAGEMENT,
    description: 'Quản lý vùng bán hàng',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ASSIGN_TERRITORIES,
    actionKey: PERMISSION_ACTION_KEYS.ASSIGN_TERRITORIES,
    actionName: 'Assign Territories',
    actionCategory: PERMISSION_ACTION_CATEGORY.TERRITORY_MANAGEMENT,
    description: 'Phân công vùng bán hàng cho nhân viên',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.SET_QUOTAS,
    actionKey: PERMISSION_ACTION_KEYS.SET_QUOTAS,
    actionName: 'Set Quotas',
    actionCategory: PERMISSION_ACTION_CATEGORY.QUOTA_MANAGEMENT,
    description: 'Thiết lập định mức bán hàng',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.TRACK_QUOTA_PERFORMANCE,
    actionKey: PERMISSION_ACTION_KEYS.TRACK_QUOTA_PERFORMANCE,
    actionName: 'Track Quota Performance',
    actionCategory: PERMISSION_ACTION_CATEGORY.QUOTA_MANAGEMENT,
    description: 'Theo dõi hiệu suất định mức',
    riskLevel: PERMISSION_RISK_LEVELS.LOW,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CALCULATE_COMMISSION,
    actionKey: PERMISSION_ACTION_KEYS.CALCULATE_COMMISSION,
    actionName: 'Calculate Commission',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMMISSION_OPERATIONS,
    description: 'Tính toán hoa hồng bán hàng',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.APPROVE_COMMISSION,
    actionKey: PERMISSION_ACTION_KEYS.APPROVE_COMMISSION,
    actionName: 'Approve Commission',
    actionCategory: PERMISSION_ACTION_CATEGORY.COMMISSION_OPERATIONS,
    description: 'Phê duyệt hoa hồng bán hàng',
    riskLevel: PERMISSION_RISK_LEVELS.CRITICAL,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CREATE_FORECAST,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_FORECAST,
    actionName: 'Create Forecast',
    actionCategory: PERMISSION_ACTION_CATEGORY.FORECAST_OPERATIONS,
    description: 'Tạo dự báo bán hàng',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.ANALYZE_FORECAST,
    actionKey: PERMISSION_ACTION_KEYS.ANALYZE_FORECAST,
    actionName: 'Analyze Forecast',
    actionCategory: PERMISSION_ACTION_CATEGORY.FORECAST_OPERATIONS,
    description: 'Phân tích dự báo và xu hướng',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },

  // Multi-level Approval Workflows (Enterprise)
  {
    id: PERMISSION_ACTION_IDS.CREATE_APPROVAL_CHAIN,
    actionKey: PERMISSION_ACTION_KEYS.CREATE_APPROVAL_CHAIN,
    actionName: 'Create Approval Chain',
    actionCategory: PERMISSION_ACTION_CATEGORY.MULTI_LEVEL_APPROVAL,
    description: 'Tạo chuỗi phê duyệt đa cấp',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.CONFIGURE_APPROVAL_RULES,
    actionKey: PERMISSION_ACTION_KEYS.CONFIGURE_APPROVAL_RULES,
    actionName: 'Configure Approval Rules',
    actionCategory: PERMISSION_ACTION_CATEGORY.MULTI_LEVEL_APPROVAL,
    description: 'Cấu hình quy tắc phê duyệt',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_ESCALATION_RULES,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_ESCALATION_RULES,
    actionName: 'Manage Escalation Rules',
    actionCategory: PERMISSION_ACTION_CATEGORY.ESCALATION_MANAGEMENT,
    description: 'Quản lý quy tắc leo thang',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.HANDLE_ESCALATION,
    actionKey: PERMISSION_ACTION_KEYS.HANDLE_ESCALATION,
    actionName: 'Handle Escalation',
    actionCategory: PERMISSION_ACTION_CATEGORY.ESCALATION_MANAGEMENT,
    description: 'Xử lý các trường hợp leo thang',
    riskLevel: PERMISSION_RISK_LEVELS.MEDIUM,
    requiresApproval: false,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.DELEGATE_PERMISSIONS,
    actionKey: PERMISSION_ACTION_KEYS.DELEGATE_PERMISSIONS,
    actionName: 'Delegate Permissions',
    actionCategory: PERMISSION_ACTION_CATEGORY.DELEGATION_OPERATIONS,
    description: 'Ủy quyền cho người dùng khác',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
  {
    id: PERMISSION_ACTION_IDS.MANAGE_DELEGATION,
    actionKey: PERMISSION_ACTION_KEYS.MANAGE_DELEGATION,
    actionName: 'Manage Delegation',
    actionCategory: PERMISSION_ACTION_CATEGORY.DELEGATION_OPERATIONS,
    description: 'Quản lý việc ủy quyền',
    riskLevel: PERMISSION_RISK_LEVELS.HIGH,
    requiresApproval: true,
    isSystemAction: true,
    isActive: true,
  },
];

// Convert action constants to data seed format
export const MKT_PERMISSION_ACTION_DATA_SEEDS: MktPermissionActionDataSeed[] =
  PERMISSION_ACTIONS_SEED.map((action, index) => ({
    id: action.id,
    actionKey: action.actionKey,
    actionName: action.actionName,
    actionCategory: action.actionCategory,
    description: action.description,
    riskLevel: action.riskLevel,
    requiresApproval: action.requiresApproval,
    isSystemAction: action.isSystemAction,
    isActive: action.isActive,
    position: (index + 1) * 100, // Position for sorting (100, 200, 300, etc.)
  }));
