import {
  MKT_CUSTOMER_LIFECYCLE_STAGE,
  MKT_CUSTOMER_STATUS,
  MKT_CUSTOMER_TIER,
  MKT_CUSTOMER_TYPE,
  MKT_CUSTOMER_DATA_SEEDS_IDS,
} from 'src/mkt-core/customer/constants/mkt-customer.constant';

export const MKT_CUSTOMER_DATA_SEED_COLUMNS = [
  'id',
  'name',
  'mktCustomerCode',
  'type',
  'email',
  'phone',
  'taxCode',
  'companyName',
  'address',
  'status',
  'tier',
  'lifecycleStage',
  'registrationDate',
  'totalOrderValue',
  'churnRiskScore',
  'engagementScore',
];

export const MKT_CUSTOMER_DATA_SEEDS = [
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    name: 'Nguyễn Văn Thành',
    mktCustomerCode: 'DIAMOND001',
    type: MKT_CUSTOMER_TYPE.BUSINESS,
    email: 'thanh.nguyen@techcorp.vn',
    phone: '+84 901 234 567',
    taxCode: '0123456789',
    companyName: 'TechCorp Vietnam',
    address: '123 Nguyễn Huệ, Quận 1, TP.HCM',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.DIAMOND,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.LOYAL,
    registrationDate: new Date('2020-01-15'),
    totalOrderValue: 5000000000, // 5 tỷ VNĐ
    churnRiskScore: 5, // Rất thấp
    engagementScore: 95,
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    name: 'Trần Thị Mai',
    mktCustomerCode: 'GOLD002',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'mai.tran@gmail.com',
    phone: '+84 987 654 321',
    taxCode: null,
    companyName: null,
    address: '456 Lê Lợi, Quận 3, TP.HCM',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.GOLD,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.CUSTOMER,
    registrationDate: new Date('2021-06-20'),
    totalOrderValue: 800000000, // 800 triệu VNĐ
    churnRiskScore: 15,
    engagementScore: 80,
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    name: 'Lê Hoàng Minh',
    mktCustomerCode: 'SILVER003',
    type: MKT_CUSTOMER_TYPE.BUSINESS,
    email: 'minh.le@startup.com',
    phone: '+84 912 345 678',
    taxCode: '0987654321',
    companyName: 'StartupX Co., Ltd',
    address: '789 Võ Văn Tần, Quận 3, TP.HCM',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.SILVER,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.CUSTOMER,
    registrationDate: new Date('2022-03-10'),
    totalOrderValue: 300000000, // 300 triệu VNĐ
    churnRiskScore: 25,
    engagementScore: 65,
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    name: 'Phạm Thị Lan',
    mktCustomerCode: 'BRONZE004',
    type: MKT_CUSTOMER_TYPE.INDIVIDUAL,
    email: 'lan.pham@email.com',
    phone: '+84 923 456 789',
    taxCode: null,
    companyName: null,
    address: '321 Trần Hưng Đạo, Quận 5, TP.HCM',
    status: MKT_CUSTOMER_STATUS.ACTIVE,
    tier: MKT_CUSTOMER_TIER.BRONZE,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.TRIAL,
    registrationDate: new Date('2023-08-15'),
    totalOrderValue: 50000000, // 50 triệu VNĐ
    churnRiskScore: 40,
    engagementScore: 45,
  },
  {
    id: MKT_CUSTOMER_DATA_SEEDS_IDS.CHURNED_CUSTOMER,
    name: 'Đỗ Văn Hùng',
    mktCustomerCode: 'CHURNED005',
    type: MKT_CUSTOMER_TYPE.BUSINESS,
    email: 'hung.do@oldcompany.vn',
    phone: '+84 934 567 890',
    taxCode: '0111222333',
    companyName: 'OldTech Solutions',
    address: '654 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
    status: MKT_CUSTOMER_STATUS.INACTIVE,
    tier: MKT_CUSTOMER_TIER.CHURNED,
    lifecycleStage: MKT_CUSTOMER_LIFECYCLE_STAGE.CHURNED,
    registrationDate: new Date('2019-11-30'),
    totalOrderValue: 120000000, // 120 triệu VNĐ (trước khi rời bỏ)
    churnRiskScore: 95, // Rất cao vì đã churn
    engagementScore: 10,
  },
];
