import {
  DEPARTMENT,
  MKT_DEPARTMENT_DATA_SEEDS_IDS,
  TEAM,
} from 'src/mkt-core/mkt-department/constants/mkt-department.constant';

export const MKT_DEPARTMENT_HIERARCHY_DATA_SEED_COLUMNS = [
  'id',
  'name',
  'parentDepartmentId',
  'childDepartmentId',

  'position',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
];

export const MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS = {
  ID_1: '59729773-746c-40f0-b9b6-e51dd8cb2442',
  ID_2: '337bce42-7f98-4bc5-8bd6-a3f662e84cc3',
  ID_3: '610e9c1c-c676-4802-9800-0e9fe5da08ef',
  ID_4: '59ac2ae9-edfc-4358-a010-d94e094d2464',
  ID_5: '6440aac2-e21f-4666-9005-dd16d716f10a',
  ID_6: '181ebdde-07f3-479f-96d9-0497f2d94046',
  ID_7: '16ea0c34-eab2-4da1-b67d-9a37c4204fd5',
  ID_8: 'e42f6ae4-6aed-486e-8b21-4b9d02401b18',
  ID_9: 'f3832293-9bad-48fd-8531-5df2c7722629',
  ID_10: '50e477e8-9139-4500-b633-b8836d370b39',
  ID_11: '62c5937a-7477-4b5d-916e-4c32b51efe21',
  ID_12: '0cde1dcd-c5af-4755-aa73-5a16c5cc36e6',
  ID_13: 'd15fc54b-142e-45da-a7c5-1cb5dab8c9c5',
  ID_14: 'f5bddd37-c0e6-4f70-8ba9-c96837609de3',
  ID_15: '427f9fdd-d3b0-4832-96ee-33d9f401b004',
  ID_16: 'a36c5acc-7650-4976-a17f-b0be6448fc1b',
  ID_17: 'd855cee6-3c07-4406-8676-aac7b695f177',
  ID_18: '09b6a040-0d8a-4544-a3eb-429fd660befc',
  ID_19: 'eb8f95d4-6706-48f5-914a-e53ff67bf9a0',
  ID_20: '56cbb6a1-faaf-40cd-ac3e-f8fb54fc33fe',
  ID_21: 'daca9fc3-c661-4fd6-95c6-5463736d9970',
  ID_22: 'eede3c48-972f-41ba-8602-cc9a0df28056',
  ID_23: 'fe332d2a-f9c9-4894-b466-250a49654a65',
  ID_24: 'f5856b2d-adb6-4ae7-bf19-b27238f29413',
  ID_25: '1a34807f-8747-454d-ac67-d018ba4c7b81',
  ID_26: '69ab24ff-6a0f-475b-919e-d350c94ba258',
  ID_27: 'd37d6765-2f1c-4c12-bbee-17e9dd9d8530',
  ID_28: '1278224a-aef9-4ab9-9a92-33398e27489e',
  ID_29: '2270f8c4-8442-493d-91d6-a90ae8637916',
  ID_30: 'd3b04558-1c44-4171-aade-cb81e421ea0a',
  ID_31: '26e516e7-07c9-42f9-a774-247eb5fcf3cf',
  ID_32: '3aec41b8-194c-4ea8-a0a0-35367a06e18b',
  ID_33: 'c5977c54-c548-48e0-920e-fa6ca4a4bb17',
  ID_34: '6db135e3-b8e4-44c9-b99d-843033d8b243',
  ID_35: 'a7f54b73-37e1-410e-b040-40e57b8caf7a',
  ID_36: '671cbbd0-151d-4b96-a665-b53f8cd72a04',
};

export const MKT_DEPARTMENT_HIERARCHY_DATA_SEEDS = [
  // Level 2 of SALES for hierarchy
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_1,
    name: 'Đội bán hàng trong nước',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_DOMESTIC],
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_2,
    name: 'Đội bán hàng quốc tế',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_INTERNATIONAL],
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_3,
    name: 'Đội bán hàng đối tác',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_PARTNER],
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_4,
    name: 'Đội bán hàng trực tuyến',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_ONLINE],
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },

  // Level 2 of SUPPORT for hierarchy
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_5,
    name: 'Đội hỗ trợ khách hàng',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_CUSTOMER],
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_6,
    name: 'Đội hỗ trợ kỹ thuật',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_TECHNICAL],
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_7,
    name: 'Đội hỗ trợ nội bộ',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_INTERNAL],
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },

  // Level 2 of ACCOUNTING for hierarchy
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_8,
    name: 'Đội phải trả',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_PAYABLE],
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_9,
    name: 'Đội phải thu',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    childDepartmentId:
      MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_RECEIVABLE],
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_10,
    name: 'Đội kiểm toán',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_AUDIT],
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_11,
    name: 'Đội thuế',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_TAX],
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },

  // Level 2 of HR for hierarchy
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_12,
    name: 'Đội tuyển dụng',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_RECRUITMENT],
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_13,
    name: 'Đội đào tạo',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_TRAINING],
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_14,
    name: 'Đội tính lương',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_PAYROLL],
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },

  // Level 2 of TECH for hierarchy
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_15,
    name: 'Đội Backend',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_BACKEND],
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_16,
    name: 'Đội Frontend',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_FRONTEND],
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_17,
    name: 'Đội DevOps',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DEVOPS],
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_18,
    name: 'Đội QA',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_QA],
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
  {
    id: MKT_DEPARTMENT_HIERARCHY_DATA_SEED_IDS.ID_19,
    name: 'Đội Data',
    parentDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    childDepartmentId: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DATA],
    position: 5,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Seeder Script',
  },
];
