import { WORKSPACE_MEMBER_DATA_SEED_IDS } from 'src/engine/workspace-manager/dev-seeder/data/constants/workspace-member-data-seeds.constant';
import {
  DEPARTMENT,
  DEPARTMENT_TYPE,
  MKT_DEPARTMENT_DATA_SEEDS_IDS,
  TEAM,
} from 'src/mkt-core/mkt-department/constants/mkt-department.constant';

export const MKT_DEPARTMENT_CODE = {
  ...DEPARTMENT,
  ...TEAM,
};

export const MKT_DEPARTMENT_DATA_SEED_COLUMNS = [
  'id',
  'departmentCode',
  'departmentType',
  'departmentName',
  'departmentNameEn',
  'description',
  'budgetCode',
  'costCenter',
  'requiresKpiTracking',
  'allowsCrossDepartmentAccess',
  'defaultKpiCategory',
  'displayOrder',
  'colorCode',
  'iconName',
  'isActive',
  'position',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
];

export const DEPARTMENT_DATA_SEEDS = [
  //Level 1
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SALES],
    departmentCode: DEPARTMENT.SALES,
    departmentType: DEPARTMENT_TYPE.DEPARTMENT,
    departmentName: 'Nhân viên kinh doanh',
    departmentNameEn: 'Sales',
    description: 'Xử lý mọi hoạt động bán hàng và quan hệ khách hàng.',
    budgetCode: 'SALES-001',
    costCenter: '1001',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Sales Performance',
    displayOrder: 1,
    colorCode: '#FF5733',
    iconName: 'sales_icon',
    isActive: true,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.SUPPORT],
    departmentCode: DEPARTMENT.SUPPORT,
    departmentType: DEPARTMENT_TYPE.DEPARTMENT,
    departmentName: 'Bộ phận hỗ trợ',
    departmentNameEn: 'Support',
    description: 'Cung cấp hỗ trợ khách hàng và hỗ trợ kỹ thuật.',
    budgetCode: 'SUPPORT-001',
    costCenter: '1002',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Customer Satisfaction',
    displayOrder: 2,
    colorCode: '#33C1FF',
    iconName: 'support_icon',
    isActive: true,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.ACCOUNTING],
    departmentCode: DEPARTMENT.ACCOUNTING,
    departmentType: DEPARTMENT_TYPE.DEPARTMENT,
    departmentName: 'Phòng kế toán',
    departmentNameEn: 'Accounting',
    description: 'Quản lý hồ sơ tài chính, giao dịch và tuân thủ.',
    budgetCode: 'ACCOUNTING-001',
    costCenter: '1003',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Financial Performance',
    displayOrder: 3,
    colorCode: '#28A745',
    iconName: 'accounting_icon',
    isActive: true,
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.HR],
    departmentCode: DEPARTMENT.HR,
    departmentType: DEPARTMENT_TYPE.DEPARTMENT,
    departmentName: 'Phòng nhân sự',
    departmentNameEn: 'Human Resources',
    description: 'Xử lý tuyển dụng, quan hệ nhân viên và chính sách nhân sự.',
    budgetCode: 'HR-001',
    costCenter: '1004',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Employee Performance',
    displayOrder: 4,
    colorCode: '#FFC107',
    iconName: 'hr_icon',
    isActive: true,
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[DEPARTMENT.TECH],
    departmentCode: DEPARTMENT.TECH,
    departmentType: DEPARTMENT_TYPE.DEPARTMENT,
    departmentName: 'Phòng công nghệ',
    departmentNameEn: 'Technology',
    description: 'Phát triển và duy trì hạ tầng công nghệ và hệ thống.',
    budgetCode: 'TECH-001',
    costCenter: '1005',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Technology Performance',
    displayOrder: 5,
    colorCode: '#6F42C1',
    iconName: 'tech_icon',
    isActive: true,
    position: 5,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
];

export const TEAM_DATA_SEEDS = [
  // Level 2 of SALES
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_DOMESTIC],
    departmentCode: TEAM.SALES_DOMESTIC,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội bán hàng trong nước',
    departmentNameEn: 'Domestic Sales Team',
    description: 'Quản lý các hoạt động bán hàng trong nước.',
    budgetCode: 'SALES-DOM-001',
    costCenter: '2001',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Domestic Sales Performance',
    displayOrder: 1,
    colorCode: '#FF8C00',
    iconName: 'domestic_sales_icon',
    isActive: true,
    position: 1,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_INTERNATIONAL],
    departmentCode: TEAM.SALES_INTERNATIONAL,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội bán hàng quốc tế',
    departmentNameEn: 'International Sales Team',
    description: 'Quản lý các hoạt động bán hàng quốc tế và xuất khẩu.',
    budgetCode: 'SALES-INT-001',
    costCenter: '2002',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'International Sales Performance',
    displayOrder: 2,
    colorCode: '#FF6347',
    iconName: 'international_sales_icon',
    isActive: true,
    position: 2,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_PARTNER],
    departmentCode: TEAM.SALES_PARTNER,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội bán hàng đối tác',
    departmentNameEn: 'Partner Sales Team',
    description: 'Quản lý các hoạt động bán hàng thông qua đối tác.',
    budgetCode: 'SALES-PAR-001',
    costCenter: '2003',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Partner Sales Performance',
    displayOrder: 3,
    colorCode: '#FF4500',
    iconName: 'partner_sales_icon',
    isActive: true,
    position: 3,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SALES_ONLINE],
    departmentCode: TEAM.SALES_ONLINE,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội bán hàng trực tuyến',
    departmentNameEn: 'Online Sales Team',
    description: 'Quản lý các hoạt động bán hàng trên nền tảng trực tuyến.',
    budgetCode: 'SALES-ONL-001',
    costCenter: '2004',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Online Sales Performance',
    displayOrder: 4,
    colorCode: '#FF7F50',
    iconName: 'online_sales_icon',
    isActive: true,
    position: 4,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  // Level 2 of SUPPORT
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_CUSTOMER],
    departmentCode: TEAM.SUPPORT_CUSTOMER,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội hỗ trợ khách hàng',
    departmentNameEn: 'Customer Support Team',
    description: 'Cung cấp hỗ trợ và giải đáp thắc mắc cho khách hàng.',
    budgetCode: 'SUP-CUS-001',
    costCenter: '2005',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Customer Support Performance',
    displayOrder: 5,
    colorCode: '#00BFFF',
    iconName: 'customer_support_icon',
    isActive: true,
    position: 5,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_TECHNICAL],
    departmentCode: TEAM.SUPPORT_TECHNICAL,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội hỗ trợ kỹ thuật',
    departmentNameEn: 'Technical Support Team',
    description: 'Cung cấp hỗ trợ kỹ thuật và xử lý sự cố.',
    budgetCode: 'SUP-TEC-001',
    costCenter: '2006',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Technical Support Performance',
    displayOrder: 6,
    colorCode: '#1E90FF',
    iconName: 'technical_support_icon',
    isActive: true,
    position: 6,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.SUPPORT_INTERNAL],
    departmentCode: TEAM.SUPPORT_INTERNAL,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội hỗ trợ nội bộ',
    departmentNameEn: 'Internal Support Team',
    description: 'Cung cấp hỗ trợ cho các bộ phận nội bộ trong công ty.',
    budgetCode: 'SUP-INT-001',
    costCenter: '2007',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'Internal Support Performance',
    displayOrder: 7,
    colorCode: '#4169E1',
    iconName: 'internal_support_icon',
    isActive: true,
    position: 7,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  // Level 2 of ACCOUNTING
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_PAYABLE],
    departmentCode: TEAM.ACCOUNTING_PAYABLE,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội kế toán thanh toán',
    departmentNameEn: 'Accounts Payable Team',
    description: 'Quản lý các khoản phải trả và thanh toán cho nhà cung cấp.',
    budgetCode: 'ACC-PAY-001',
    costCenter: '2008',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Payable Management Performance',
    displayOrder: 8,
    colorCode: '#32CD32',
    iconName: 'accounts_payable_icon',
    isActive: true,
    position: 8,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_RECEIVABLE],
    departmentCode: TEAM.ACCOUNTING_RECEIVABLE,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội kế toán thu hồi',
    departmentNameEn: 'Accounts Receivable Team',
    description: 'Quản lý các khoản phải thu và thu hồi nợ từ khách hàng.',
    budgetCode: 'ACC-REC-001',
    costCenter: '2009',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Receivable Management Performance',
    displayOrder: 9,
    colorCode: '#90EE90',
    iconName: 'accounts_receivable_icon',
    isActive: true,
    position: 9,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_AUDIT],
    departmentCode: TEAM.ACCOUNTING_AUDIT,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội kiểm toán',
    departmentNameEn: 'Audit Team',
    description: 'Thực hiện kiểm toán nội bộ và đảm bảo tuân thủ quy định.',
    budgetCode: 'ACC-AUD-001',
    costCenter: '2010',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'Audit Performance',
    displayOrder: 10,
    colorCode: '#228B22',
    iconName: 'audit_icon',
    isActive: true,
    position: 10,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.ACCOUNTING_TAX],
    departmentCode: TEAM.ACCOUNTING_TAX,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội kế toán thuế',
    departmentNameEn: 'Tax Team',
    description: 'Quản lý các vấn đề thuế và tuân thủ quy định thuế.',
    budgetCode: 'ACC-TAX-001',
    costCenter: '2011',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Tax Management Performance',
    displayOrder: 11,
    colorCode: '#008000',
    iconName: 'tax_icon',
    isActive: true,
    position: 11,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  // Level 2 of HR
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_RECRUITMENT],
    departmentCode: TEAM.HR_RECRUITMENT,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội tuyển dụng',
    departmentNameEn: 'Recruitment Team',
    description: 'Quản lý quy trình tuyển dụng và thu hút nhân tài.',
    budgetCode: 'HR-REC-001',
    costCenter: '2012',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Recruitment Performance',
    displayOrder: 12,
    colorCode: '#FFD700',
    iconName: 'recruitment_icon',
    isActive: true,
    position: 12,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_TRAINING],
    departmentCode: TEAM.HR_TRAINING,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội đào tạo',
    departmentNameEn: 'Training Team',
    description: 'Phát triển và thực hiện các chương trình đào tạo nhân viên.',
    budgetCode: 'HR-TRA-001',
    costCenter: '2013',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'Training Performance',
    displayOrder: 13,
    colorCode: '#F0E68C',
    iconName: 'training_icon',
    isActive: true,
    position: 13,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.HR_PAYROLL],
    departmentCode: TEAM.HR_PAYROLL,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội tính lương',
    departmentNameEn: 'Payroll Team',
    description: 'Quản lý lương bổng và các khoản thanh toán cho nhân viên.',
    budgetCode: 'HR-PAY-001',
    costCenter: '2014',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Payroll Performance',
    displayOrder: 14,
    colorCode: '#DAA520',
    iconName: 'payroll_icon',
    isActive: true,
    position: 14,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  // Level 2 of TECH
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_BACKEND],
    departmentCode: TEAM.TECH_BACKEND,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội phát triển Backend',
    departmentNameEn: 'Backend Development Team',
    description: 'Phát triển và duy trì các hệ thống backend và API.',
    budgetCode: 'TECH-BE-001',
    costCenter: '2015',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Backend Development Performance',
    displayOrder: 15,
    colorCode: '#9370DB',
    iconName: 'backend_icon',
    isActive: true,
    position: 15,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_FRONTEND],
    departmentCode: TEAM.TECH_FRONTEND,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội phát triển Frontend',
    departmentNameEn: 'Frontend Development Team',
    description: 'Phát triển giao diện người dùng và trải nghiệm người dùng.',
    budgetCode: 'TECH-FE-001',
    costCenter: '2016',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'Frontend Development Performance',
    displayOrder: 16,
    colorCode: '#8A2BE2',
    iconName: 'frontend_icon',
    isActive: true,
    position: 16,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DEVOPS],
    departmentCode: TEAM.TECH_DEVOPS,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội DevOps',
    departmentNameEn: 'DevOps Team',
    description: 'Quản lý hạ tầng, triển khai và vận hành hệ thống.',
    budgetCode: 'TECH-DO-001',
    costCenter: '2017',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'DevOps Performance',
    displayOrder: 17,
    colorCode: '#7B68EE',
    iconName: 'devops_icon',
    isActive: true,
    position: 17,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_QA],
    departmentCode: TEAM.TECH_QA,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội đảm bảo chất lượng',
    departmentNameEn: 'Quality Assurance Team',
    description: 'Đảm bảo chất lượng sản phẩm và thực hiện kiểm thử.',
    budgetCode: 'TECH-QA-001',
    costCenter: '2018',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: false,
    defaultKpiCategory: 'QA Performance',
    displayOrder: 18,
    colorCode: '#6A5ACD',
    iconName: 'qa_icon',
    isActive: true,
    position: 18,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
  {
    id: MKT_DEPARTMENT_DATA_SEEDS_IDS[TEAM.TECH_DATA],
    departmentCode: TEAM.TECH_DATA,
    departmentType: DEPARTMENT_TYPE.TEAM,
    departmentName: 'Đội dữ liệu',
    departmentNameEn: 'Data Team',
    description:
      'Quản lý, phân tích dữ liệu và phát triển các giải pháp dữ liệu.',
    budgetCode: 'TECH-DA-001',
    costCenter: '2019',
    requiresKpiTracking: true,
    allowsCrossDepartmentAccess: true,
    defaultKpiCategory: 'Data Management Performance',
    displayOrder: 19,
    colorCode: '#483D8B',
    iconName: 'data_icon',
    isActive: true,
    position: 19,
    createdBySource: 'API',
    createdByWorkspaceMemberId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    createdByName: 'Tim',
  },
];

export const MKT_DEPARTMENT_DATA_SEEDS = [
  ...DEPARTMENT_DATA_SEEDS,
  ...TEAM_DATA_SEEDS,
];
