import { MKT_CUSTOMER_DATA_SEEDS_IDS } from 'src/mkt-core/customer/constants/mkt-customer.constant';
import { ORDER_STATUS, SINVOICE_STATUS } from 'src/mkt-core/order/constants';
import { PAYMENT_STATUS } from 'src/mkt-core/order/constants/payment-status.constants';
import { GenericComboSnapshot } from 'src/mkt-core/order/types';
import { WORKSPACE_MEMBER_DATA_SEED_IDS } from 'src/engine/workspace-manager/dev-seeder/data/constants/workspace-member-data-seeds.constant';
import { PromotionSnapshot } from 'src/mkt-core/mkt-promotion/types/promotion.types';
import { DateTimeUtils } from 'src/mkt-core/utils/date-time.utils';

// ============================================
// PAYMENT DEADLINE SOURCE CONSTANTS
// ============================================

export const PAYMENT_DEADLINE_SOURCE = {
  GLOBAL: 'GLOBAL',
  PRODUCT: 'PRODUCT',
  CUSTOMER_TYPE: 'CUSTOMER_TYPE',
  RESELLER_TIER: 'RESELLER_TIER',
  MANUAL: 'MANUAL',
} as const;

type PaymentDeadlineSource =
  (typeof PAYMENT_DEADLINE_SOURCE)[keyof typeof PAYMENT_DEADLINE_SOURCE];

// ============================================
// SEED DATA TYPE
// ============================================

type MktOrderDataSeed = {
  id: string;
  name: string;
  position: number;
  orderCode: string;
  status: string;
  subtotal: number;
  tax: number;
  discount: number;
  discountPercent: number;
  refundAmount: number;
  totalAmount: number;
  currency: string;
  note: string;
  trialLicense: boolean;
  requireContract: boolean;
  sInvoiceStatus: string;
  licenseStatus: string | null;
  metadata: JSON | null;
  accountingConfirmed: boolean;
  salePaymentConfirmed: boolean;
  accountOwnerId: string;
  mktCustomerId: string;
  createdById: string;
  // Promotion fields
  couponCode: string | null;
  promotionDiscount: number;
  appliedPromotions: PromotionSnapshot[] | null;
  // Combo fields
  appliedCombos: GenericComboSnapshot[] | null;
  comboDiscount: number;
  // Multi-payment fields
  paidAmount: number;
  remainingAmount: number;
  paymentStatus: string;
  // Payment deadline fields (New Payment Flow)
  paymentDeadline: Date | null;
  paymentDeadlineSource: PaymentDeadlineSource | null;
  lockedAt: Date | null;
  lockedReason: string | null;
  remindersSent: number;
  lastReminderAt: Date | null;
  // Dual-metric revenue
  completedAt: Date | null;
  // Optimistic locking
  version: number;
  // Override createdAt for historical seed data
  createdAt?: Date;
};

// prettier-ignore
export const MKT_ORDER_DATA_SEED_COLUMNS: (keyof MktOrderDataSeed)[] = [
  'id',
  'name',
  'position',
  'orderCode',
  'status',
  'subtotal',
  'tax',
  'discount',
  'discountPercent',
  'refundAmount',
  'totalAmount',
  'currency',
  'note',
  'trialLicense',
  'requireContract',
  'sInvoiceStatus',
  'licenseStatus',
  'metadata',
  'accountingConfirmed',
  'salePaymentConfirmed',
  'accountOwnerId',
  'mktCustomerId',
  'createdById',
  'couponCode',
  'promotionDiscount',
  'appliedPromotions',
  // Combo fields
  'appliedCombos',
  'comboDiscount',
  // Multi-payment fields
  'paidAmount',
  'remainingAmount',
  'paymentStatus',
  // Payment deadline fields (New Payment Flow)
  'paymentDeadline',
  'paymentDeadlineSource',
  'lockedAt',
  'lockedReason',
  'remindersSent',
  'lastReminderAt',
  // Dual-metric revenue
  'completedAt',
  // Optimistic locking
  'version',
];

// Default promotion fields for seed data
const DEFAULT_PROMOTION_FIELDS = {
  couponCode: null,
  promotionDiscount: 0,
  appliedPromotions: null,
};

// Default combo fields for seed data
const DEFAULT_COMBO_FIELDS = {
  appliedCombos: null,
  comboDiscount: 0,
};

// ============================================
// PAYMENT DEADLINE HELPERS
// ============================================

/**
 * Default payment deadline fields for completed/legacy orders
 * (Orders without new payment flow)
 */
const DEFAULT_PAYMENT_DEADLINE_FIELDS = {
  paymentDeadline: null,
  paymentDeadlineSource: null,
  lockedAt: null,
  lockedReason: null,
  remindersSent: 0,
  lastReminderAt: null,
  completedAt: null,
  version: 1,
};

/**
 * Create payment deadline fields for PROCESSING orders
 * (Orders confirmed, license issued with PENDING_PAYMENT, waiting for payment)
 *
 * @param hoursFromNow - Hours from now for payment deadline
 * @param source - Source of deadline configuration
 * @param remindersSent - Number of reminders already sent
 */
const CREATE_PROCESSING_DEADLINE_FIELDS = (
  hoursFromNow: number,
  source: PaymentDeadlineSource,
  remindersSent = 0,
): Pick<
  MktOrderDataSeed,
  | 'paymentDeadline'
  | 'paymentDeadlineSource'
  | 'lockedAt'
  | 'lockedReason'
  | 'remindersSent'
  | 'lastReminderAt'
  | 'completedAt'
  | 'version'
> => {
  const NOW = DateTimeUtils.now();
  const DEADLINE = DateTimeUtils.add(NOW, { hours: hoursFromNow });
  const LAST_REMINDER =
    remindersSent > 0 ? DateTimeUtils.subtract(NOW, { hours: 2 }) : null;

  return {
    paymentDeadline: DateTimeUtils.toDate(DEADLINE) ?? null,
    paymentDeadlineSource: source,
    lockedAt: null,
    lockedReason: null,
    remindersSent,
    lastReminderAt: LAST_REMINDER
      ? (DateTimeUtils.toDate(LAST_REMINDER) ?? null)
      : null,
    completedAt: null,
    version: 1,
  };
};

/**
 * Create payment deadline fields for LOCKED orders
 * (Orders locked due to overdue payment)
 *
 * @param hoursAgoLocked - Hours ago when the order was locked
 * @param source - Source of deadline configuration
 * @param reason - Reason for locking
 */
const CREATE_LOCKED_DEADLINE_FIELDS = (
  hoursAgoLocked: number,
  source: PaymentDeadlineSource,
  reason = 'Payment overdue - deadline exceeded',
): Pick<
  MktOrderDataSeed,
  | 'paymentDeadline'
  | 'paymentDeadlineSource'
  | 'lockedAt'
  | 'lockedReason'
  | 'remindersSent'
  | 'lastReminderAt'
  | 'completedAt'
  | 'version'
> => {
  const NOW = DateTimeUtils.now();
  const LOCKED_AT = DateTimeUtils.subtract(NOW, { hours: hoursAgoLocked });
  // Deadline was before lock time (e.g., 24h before locked)
  const DEADLINE = DateTimeUtils.subtract(LOCKED_AT, { minutes: 1 });
  // Last reminder was sent ~30 minutes before deadline
  const LAST_REMINDER = DateTimeUtils.subtract(DEADLINE, { minutes: 30 });

  return {
    paymentDeadline: DateTimeUtils.toDate(DEADLINE) ?? null,
    paymentDeadlineSource: source,
    lockedAt: DateTimeUtils.toDate(LOCKED_AT) ?? null,
    lockedReason: reason,
    remindersSent: 3, // All 3 reminders were sent (6h, 2h, 30min)
    lastReminderAt: DateTimeUtils.toDate(LAST_REMINDER) ?? null,
    completedAt: null,
    version: 1,
  };
};

/**
 * Create payment fields for seed data
 * For completed orders: paidAmount = totalAmount, remainingAmount = 0, paymentStatus = PAID
 * For pending orders: paidAmount = 0, remainingAmount = totalAmount, paymentStatus = PENDING
 */
const CREATE_PAYMENT_FIELDS = (
  totalAmount: number,
  isPaid: boolean,
): { paidAmount: number; remainingAmount: number; paymentStatus: string } => ({
  paidAmount: isPaid ? totalAmount : 0,
  remainingAmount: isPaid ? 0 : totalAmount,
  paymentStatus: isPaid ? PAYMENT_STATUS.PAID : PAYMENT_STATUS.PENDING,
});

//prettier-ignore
export const MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS = {
  // TIM orders - January 2026
  PREV_TIM_1: '1a2b3c4d-1e2f-4a3b-9c4d-5e6f7a8b9c0d',
  PREV_TIM_2: '2b3c4d5e-2f3a-4b4c-8d5e-6f7a8b9c0d1e',
  PREV_TIM_3: '3c4d5e6f-3a4b-4c5d-ae6f-7b8c9d0e1f2a',
  // JONY orders - January 2026
  PREV_JONY_1: '4d5e6f7a-4b5c-4d6e-bf7a-8c9d0e1f2a3b',
  PREV_JONY_2: '5e6f7a8b-5c6d-4e7f-9a8b-9d0e1f2a3b4c',
  PREV_JONY_3: '6f7a8b9c-6d7e-4f8a-ab9c-0e1f2a3b4c5d',
  // PHIL orders - January 2026
  PREV_PHIL_1: '7a8b9c0d-7e8f-4a9b-8c0d-1f2a3b4c5d6e',
  PREV_PHIL_2: '8b9c0d1e-8f9a-4b0c-9d1e-2a3b4c5d6e7f',
  PREV_PHIL_3: '9c0d1e2f-9a0b-4c1d-be2f-3b4c5d6e7f8a',
  // JANE orders - January 2026
  PREV_JANE_1: '0d1e2f3a-0b1c-4d2e-af3a-4c5d6e7f8a9b',
  PREV_JANE_2: '1e2f3a4b-1c2d-4e3f-8a4b-5d6e7f8a9b0c',
};

//prettier-ignore
export const MKT_ORDER_DATA_SEEDS_IDS = {
  ID_1: '774f7b42-e0e6-45b7-9804-ea6b89c0bf8b',
  ID_2: '09f33908-d459-44c3-999e-97f42faf6d30',
  ID_3: '0200e865-6bb2-4645-904c-1ee9fc021c1e',
  ID_4: 'd4a05376-ec12-4f11-92d9-cd5722d70c0b',
  ID_5: '8a361cb9-f40a-4b03-8e02-fdd6e13e8f29',
  ID_6: 'd7cfdf7f-97c8-47ee-a2f9-5eaa8d3af929',
  ID_7: '642c3b7b-6fff-4fbb-a096-7f5432260ed8',
  ID_8: '52dd35b6-2b2a-42e1-be7c-589295a83868',
  ID_9: '28e054f6-4ce2-48aa-93cc-89519a3cf267',
  ID_10: '1899837e-f89f-44ee-8aea-b9a4647cdae7',
  ID_11: '7359947a-4a39-4b45-897f-6fa031b8eab6',
  ID_12: '611d615e-6c3b-4652-9087-e50043ddf260',
  ID_13: 'b9433b83-0e42-4c58-a380-dfd0a69905d7',
  ID_14:"1ddffa25-0386-4153-94c4-db2cf1184394",
  GOLD_ORDER_1:"01f52114-52d6-4e77-8a1a-5cf064ac8451",
GOLD_ORDER_2:"b23758f2-8d3c-45c7-b648-f4f4e6339bf2",
GOLD_ORDER_3:"e231da12-85c6-46a9-977d-ef6daea6aa3f",
DIAMOND_ORDER_1:"a75e9363-dd0c-493b-92bc-e4364f7f9f9b",
DIAMOND_ORDER_2:"18d5e4e1-2a85-4e92-b3a6-93393e971b67",
DIAMOND_ORDER_3:"da13679d-aefd-46f9-b567-ab3582ed65f5",
DIAMOND_ORDER_4:"1fc4325c-2d66-4b80-98cb-07852369147a",
DIAMOND_ORDER_5:"11a8b9db-cdff-4a94-9a3f-de70d753c87b",
DIAMOND_ORDER_6:"7675d910-ce6f-4974-9e8e-63e8f1ddb838",
DIAMOND_ORDER_7:"86293d74-2203-468c-ac24-580a623a8a3d",
DIAMOND_ORDER_8:"15b26e73-17fa-4dc4-a2ca-fcc609c74466",
DIAMOND_ORDER_9:"965972e5-0e61-489a-9ed0-22a790e618b6",
DIAMOND_ORDER_10:"ddcb8b82-52ac-4fa0-86db-c151848f6a6c",
DIAMOND_ORDER_11:"187bfea8-c0cb-4797-9012-e15e6aa13568",
DIAMOND_ORDER_12:"532c46af-36c1-44e5-bfe3-f49ed2f6611d",
DIAMOND_ORDER_13:"984e8a9a-b30e-49d4-9cbd-0ab1329e34f9",
DIAMOND_ORDER_14:"196eb616-07dc-402a-a1eb-611cdab489f3",
DIAMOND_ORDER_15:"f0afcee4-12c3-4beb-9d9f-c7bad67b43d7",
DIAMOND_ORDER_16:"996102ff-b0c2-45f1-b95e-14ffe3d9a262",
DIAMOND_ORDER_17:"b882a0c9-27dd-4cdd-8239-823ec11f3ee4",
DIAMOND_ORDER_18:"37b8f1be-0b69-4768-b5cc-cbda101c3163",
DIAMOND_ORDER_19:"faac3d90-bdb1-4b42-a0c0-88c965eee9ff",
DIAMOND_ORDER_20:"f840d091-cf46-4d5a-99c9-d2259cacd3e3",
  // New Payment Flow - PROCESSING orders (waiting for payment, license issued with PENDING_PAYMENT)
  PROCESSING_ORDER_1: 'c1a2b3c4-d5e6-f7a8-b9c0-1234567890ab',
  PROCESSING_ORDER_2: 'd2b3c4d5-e6f7-a8b9-c0d1-234567890abc',
  PROCESSING_ORDER_3: 'e3c4d5e6-f7a8-b9c0-d1e2-34567890abcd',
  // New Payment Flow - LOCKED orders (overdue, license locked on MKT Server)
  LOCKED_ORDER_1: 'f4d5e6f7-a8b9-c0d1-e2f3-4567890abcde',
  LOCKED_ORDER_2: 'a5e6f7a8-b9c0-d1e2-f3a4-567890abcdef',
};

// prettier-ignore
export const MKT_ORDER_DATA_SEEDS: MktOrderDataSeed[] = [
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_1,
    name: 'Đơn hàng MKT Care Package - Gói chăm sóc Facebook',
    position: 1,
    orderCode: 'MKT-CARE-2024-001',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 11000000,
    tax: 1100000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 12100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Care Basic 1 năm và 2 năm cho khách hàng doanh nghiệp',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(12100000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_2,
    name: 'Đơn hàng MKT Viral Package - Gói viral video',
    position: 2,
    orderCode: 'MKT-VIRAL-2024-002',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 16000000,
    tax: 1600000,
    discount: 500000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 17100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Viral Basic 1 năm (2 license) và vĩnh viễn cho agency marketing',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(17100000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_3,
    name: 'Đơn hàng MKT UID Package - Gói phân tích data',
    position: 3,
    orderCode: 'MKT-UID-2024-003',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 6000000,
    tax: 600000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 6600000,
    currency: 'VND',
    note: 'Đơn hàng 3 license MKT UID Basic 1 năm cho team phân tích dữ liệu',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    licenseStatus: null,
    accountingConfirmed: false,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(6600000, false),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_4,
    name: 'Đơn hàng MKT Insta Package - Gói Instagram marketing',
    position: 4,
    orderCode: 'MKT-INSTA-2024-004',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 15000000,
    tax: 1500000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 16500000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Insta Basic 2 năm và vĩnh viễn cho influencer marketing',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(16500000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_5,
    name: 'Đơn hàng MKT Tube Package - Gói quản lý YouTube',
    position: 5,
    orderCode: 'MKT-TUBE-2024-005',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 9000000,
    tax: 900000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 9900000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Tube Basic 1 năm (2 license) và vĩnh viễn cho MCN',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(9900000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_6,
    name: 'Đơn hàng MKT Post Package - Gói đăng bài Facebook',
    position: 6,
    orderCode: 'MKT-POST-2024-006',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 3000000,
    tax: 300000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 3300000,
    currency: 'VND',
    note: 'Đơn hàng MKT Post Basic 1 năm cho shop bán hàng online',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(3300000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_7,
    name: 'Đơn hàng MKT Zalo Package - Gói marketing Zalo',
    position: 7,
    orderCode: 'MKT-ZALO-2024-007',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Đơn hàng MKT Zalo Basic 2 năm cho doanh nghiệp B2B',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(5500000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_8,
    name: 'Đơn hàng MKT Group Package - Gói quản lý Group Facebook',
    position: 8,
    orderCode: 'MKT-GROUP-2024-008',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 16000000,
    tax: 1600000,
    discount: 1000000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 17600000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Group Basic 1 năm (2 license) và vĩnh viễn cho community manager',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(17600000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_9,
    name: 'Đơn hàng MKT Twitter Package - Gói marketing Twitter/X',
    position: 9,
    orderCode: 'MKT-TWITTER-2024-009',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 3000000,
    tax: 300000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 3300000,
    currency: 'VND',
    note: 'Đơn hàng MKT Twitter Basic 1 năm - thanh toán thất bại',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.FAILED,
    licenseStatus: null,
    accountingConfirmed: false,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(3300000, false),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_10,
    name: 'Đơn hàng MKT Page Package - Gói quản lý Fanpage',
    position: 10,
    orderCode: 'MKT-PAGE-2024-010',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Đơn hàng MKT Page Basic 2 năm cho agency quản lý fanpage',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(5500000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_11,
    name: 'Đơn hàng MKT Maps Package - Gói scan Google Maps',
    position: 11,
    orderCode: 'MKT-MAPS-2024-011',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 9000000,
    tax: 900000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 9900000,
    currency: 'VND',
    note: 'Đơn hàng 3 license MKT Maps Basic 1 năm cho team lead generation',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(9900000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_12,
    name: 'Đơn hàng MKT Maps Forever - Gói vĩnh viễn Google Maps',
    position: 12,
    orderCode: 'MKT-MAPS-FOREVER-2024-012',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 10000000,
    tax: 1000000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 11000000,
    currency: 'VND',
    note: 'Đơn hàng MKT Maps Basic vĩnh viễn cho doanh nghiệp lớn',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(11000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_13,
    name: 'Đơn hàng Combo Package - Gói tổng hợp UID + Post',
    position: 13,
    orderCode: 'MKT-COMBO-2024-013',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 8500000,
    tax: 850000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 9350000,
    currency: 'VND',
    note: 'Đơn hàng combo MKT UID Basic 2 năm + MKT Post Basic 2 năm - đã hủy',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    licenseStatus: null,
    accountingConfirmed: false,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(9350000, false),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_14,
    name: 'Đơn hàng MKT Care Package - Gói chăm sóc Facebook',
    position: 14,
    orderCode: 'MKT-CARE-2024-014',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 11000000,
    tax: 1100000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 12100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Care Basic 1 năm và 2 năm cho khách hàng doanh nghiệp',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(12100000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  // GOLD_CUSTOMER orders
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_1,
    name: 'Đơn hàng MKT Premium Care - Gói chăm sóc cao cấp',
    position: 15,
    orderCode: 'MKT-PREMIUM-2024-015',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 25000000,
    tax: 2500000,
    discount: 1000000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 26500000,
    currency: 'VND',
    note: 'Gói chăm sóc khách hàng VIP với tư vấn 24/7',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(26500000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_2,
    name: 'Đơn hàng MKT Analytics Pro - Gói phân tích nâng cao',
    position: 16,
    orderCode: 'MKT-ANALYTICS-2024-016',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 18000000,
    tax: 1800000,
    discount: 500000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 19300000,
    currency: 'VND',
    note: 'Gói phân tích dữ liệu khách hàng với AI insights',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(19300000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_3,
    name: 'Đơn hàng MKT Multi-Channel - Gói đa nền tảng',
    position: 17,
    orderCode: 'MKT-MULTI-2024-017',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 22000000,
    tax: 2200000,
    discount: 800000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 23400000,
    currency: 'VND',
    note: 'Quản lý marketing trên tất cả nền tảng social media',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(23400000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  // DIAMOND_CUSTOMER orders
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_1,
    name: 'Đơn hàng MKT Enterprise Suite - Gói doanh nghiệp đầy đủ',
    position: 18,
    orderCode: 'MKT-ENT-2024-018',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 500000000,
    tax: 50000000,
    discount: 25000000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 525000000,
    currency: 'VND',
    note: 'Giải pháp toàn diện cho doanh nghiệp lớn với dedicated support',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(525000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_2,
    name: 'Đơn hàng MKT AI Analytics - Gói phân tích AI cao cấp',
    position: 19,
    orderCode: 'MKT-AI-2024-019',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 300000000,
    tax: 30000000,
    discount: 15000000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 315000000,
    currency: 'VND',
    note: 'Phân tích dữ liệu với AI và machine learning',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(315000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_3,
    name: 'Đơn hàng MKT Custom Development - Phát triển tùy chỉnh',
    position: 20,
    orderCode: 'MKT-DEV-2024-020',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 800000000,
    tax: 80000000,
    discount: 40000000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 840000000,
    currency: 'VND',
    note: 'Phát triển tính năng riêng theo yêu cầu doanh nghiệp',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(840000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_4,
    name: 'Đơn hàng MKT Global Expansion - Gói mở rộng quốc tế',
    position: 21,
    orderCode: 'MKT-GLOBAL-2024-021',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 450000000,
    tax: 45000000,
    discount: 20000000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 475000000,
    currency: 'VND',
    note: 'Hỗ trợ marketing đa quốc gia với localization',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(475000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_5,
    name: 'Đơn hàng MKT White Label - Gói thương hiệu riêng',
    position: 22,
    orderCode: 'MKT-WHITE-2024-022',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 600000000,
    tax: 60000000,
    discount: 30000000,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 630000000,
    currency: 'VND',
    note: 'Giải pháp white-label cho reseller và partner',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: null,
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(630000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_6,
    name: 'Đơn hàng MKT API Premium - Gói API cao cấp',
    position: 23,
    orderCode: 'MKT-API-2024-023',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 250000000,
    tax: 25000000,
    discount: 12000000,
    discountPercent: 4.8,
    refundAmount: 0,
    totalAmount: 263000000,
    currency: 'VND',
    note: 'API unlimited với rate limit cao cho tích hợp hệ thống',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(263000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_7,
    name: 'Đơn hàng MKT Training & Certification - Đào tạo chuyên sâu',
    position: 24,
    orderCode: 'MKT-TRAIN-2024-024',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 120000000,
    tax: 12000000,
    discount: 5000000,
    discountPercent: 4.17,
    refundAmount: 0,
    totalAmount: 127000000,
    currency: 'VND',
    note: 'Chương trình đào tạo và chứng nhận cho team marketing',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(127000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_8,
    name: 'Đơn hàng MKT Security Plus - Gói bảo mật nâng cao',
    position: 25,
    orderCode: 'MKT-SEC-2024-025',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 180000000,
    tax: 18000000,
    discount: 8000000,
    discountPercent: 4.44,
    refundAmount: 0,
    totalAmount: 190000000,
    currency: 'VND',
    note: 'Bảo mật cấp enterprise với SSO và audit logs',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(190000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_9,
    name: 'Đơn hàng MKT Data Lake - Kho dữ liệu lớn',
    position: 26,
    orderCode: 'MKT-LAKE-2024-026',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 350000000,
    tax: 35000000,
    discount: 17000000,
    discountPercent: 4.86,
    refundAmount: 0,
    totalAmount: 368000000,
    currency: 'VND',
    note: 'Giải pháp lưu trữ và xử lý dữ liệu quy mô lớn',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(368000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_10,
    name: 'Đơn hàng MKT Automation Studio - Studio tự động hóa',
    position: 27,
    orderCode: 'MKT-AUTO-2024-027',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 280000000,
    tax: 28000000,
    discount: 14000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 294000000,
    currency: 'VND',
    note: 'Tự động hóa toàn bộ quy trình marketing với workflow',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(294000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_11,
    name: 'Đơn hàng MKT Performance Monitoring - Giám sát hiệu suất',
    position: 28,
    orderCode: 'MKT-PERF-2024-028',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 150000000,
    tax: 15000000,
    discount: 7000000,
    discountPercent: 4.67,
    refundAmount: 0,
    totalAmount: 158000000,
    currency: 'VND',
    note: 'Giám sát real-time hiệu suất marketing campaigns',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(158000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_12,
    name: 'Đơn hàng MKT Compliance Suite - Gói tuân thủ quy định',
    position: 29,
    orderCode: 'MKT-COMP-2024-029',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 200000000,
    tax: 20000000,
    discount: 10000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 210000000,
    currency: 'VND',
    note: 'Tuân thủ GDPR, CCPA và các quy định bảo mật dữ liệu',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(210000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_13,
    name: 'Đơn hàng MKT Mobile SDK - Bộ phát triển mobile',
    position: 30,
    orderCode: 'MKT-SDK-2024-030',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 320000000,
    tax: 32000000,
    discount: 16000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 336000000,
    currency: 'VND',
    note: 'SDK tích hợp marketing cho ứng dụng mobile',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(336000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_14,
    name: 'Đơn hàng MKT Edge Computing - Tính toán cạnh',
    position: 31,
    orderCode: 'MKT-EDGE-2024-031',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 400000000,
    tax: 40000000,
    discount: 20000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 420000000,
    currency: 'VND',
    note: 'Xử lý dữ liệu marketing tại edge để giảm latency',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(420000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_15,
    name: 'Đơn hàng MKT Blockchain Analytics - Phân tích blockchain',
    position: 32,
    orderCode: 'MKT-BLOCK-2024-032',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 600000000,
    tax: 60000000,
    discount: 30000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 630000000,
    currency: 'VND',
    note: 'Phân tích marketing trong ecosystem blockchain và Web3',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(630000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_16,
    name: 'Đơn hàng MKT IoT Integration - Tích hợp IoT',
    position: 33,
    orderCode: 'MKT-IOT-2024-033',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 380000000,
    tax: 38000000,
    discount: 19000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 399000000,
    currency: 'VND',
    note: 'Tích hợp dữ liệu marketing từ thiết bị IoT',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(399000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_17,
    name: 'Đơn hàng MKT Quantum Computing - Tính toán lượng tử',
    position: 34,
    orderCode: 'MKT-QUANTUM-2024-034',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 1200000000,
    tax: 120000000,
    discount: 60000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 1260000000,
    currency: 'VND',
    note: 'Ứng dụng quantum computing trong optimization marketing',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(1260000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_18,
    name: 'Đơn hàng MKT VR/AR Analytics - Phân tích thực tế ảo',
    position: 35,
    orderCode: 'MKT-VR-2024-035',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 500000000,
    tax: 50000000,
    discount: 25000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 525000000,
    currency: 'VND',
    note: 'Phân tích hành vi người dùng trong môi trường VR/AR',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(525000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_19,
    name: 'Đơn hàng MKT Neural Networks - Mạng nơ-ron nhân tạo',
    position: 36,
    orderCode: 'MKT-NEURAL-2024-036',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 750000000,
    tax: 75000000,
    discount: 37000000,
    discountPercent: 4.93,
    refundAmount: 0,
    totalAmount: 788000000,
    currency: 'VND',
    note: 'Mạng nơ-ron sâu cho dự đoán hành vi khách hàng',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(788000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_20,
    name: 'Đơn hàng MKT Metaverse Platform - Nền tảng metaverse',
    position: 37,
    orderCode: 'MKT-META-2024-037',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 2000000000,
    tax: 200000000,
    discount: 100000000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 2100000000,
    currency: 'VND',
    note: 'Nền tảng marketing toàn diện trong metaverse',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(2100000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
  },

  // ============================================
  // PROCESSING ORDERS (New Payment Flow)
  // License đã cấp với status PENDING_PAYMENT, đang chờ thanh toán
  // ============================================
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.PROCESSING_ORDER_1,
    name: 'Đơn hàng MKT Care Pro - Đang chờ thanh toán (deadline 12h)',
    position: 38,
    orderCode: 'MKT-PROC-2024-038',
    status: ORDER_STATUS.PROCESSING,
    subtotal: 15000000,
    tax: 1500000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 16500000,
    currency: 'VND',
    note: 'Đơn hàng PROCESSING - License đã cấp với PENDING_PAYMENT, deadline còn 12h',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    licenseStatus: 'PENDING_PAYMENT',
    accountingConfirmed: false,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(16500000, false),
    ...CREATE_PROCESSING_DEADLINE_FIELDS(12, PAYMENT_DEADLINE_SOURCE.GLOBAL, 1),
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.PROCESSING_ORDER_2,
    name: 'Đơn hàng MKT Enterprise - Sale đã xác nhận (PROTECTED từ auto-lock)',
    position: 39,
    orderCode: 'MKT-PROC-2024-039',
    status: ORDER_STATUS.PROCESSING,
    subtotal: 50000000,
    tax: 5000000,
    discount: 2500000,
    discountPercent: 5.0,
    refundAmount: 0,
    totalAmount: 52500000,
    currency: 'VND',
    note: 'Đơn hàng PROCESSING - Sale đã xác nhận thanh toán, được bảo vệ khỏi auto-lock dù quá deadline',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    licenseStatus: 'PENDING_PAYMENT',
    accountingConfirmed: false,
    // Sale đã xác nhận - salePaymentConfirmed = true, deadline đã quá nhưng không bị lock
    salePaymentConfirmed: true,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(52500000, false),
    ...CREATE_PROCESSING_DEADLINE_FIELDS(-24, PAYMENT_DEADLINE_SOURCE.CUSTOMER_TYPE, 2),
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.PROCESSING_ORDER_3,
    name: 'Đơn hàng MKT Reseller Pack - Đang chờ thanh toán (deadline 72h, Gold tier)',
    position: 40,
    orderCode: 'MKT-PROC-2024-040',
    status: ORDER_STATUS.PROCESSING,
    subtotal: 100000000,
    tax: 10000000,
    discount: 10000000,
    discountPercent: 10.0,
    refundAmount: 0,
    totalAmount: 100000000,
    currency: 'VND',
    note: 'Đơn hàng PROCESSING - Đại lý Gold tier có deadline 72h (3 ngày)',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    licenseStatus: 'PENDING_PAYMENT',
    accountingConfirmed: false,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(100000000, false),
    ...CREATE_PROCESSING_DEADLINE_FIELDS(72, PAYMENT_DEADLINE_SOURCE.RESELLER_TIER, 0),
  },

  // ============================================
  // LOCKED ORDERS (New Payment Flow)
  // License bị khóa trên MKT Server do quá hạn thanh toán
  // ============================================
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.LOCKED_ORDER_1,
    name: 'Đơn hàng MKT Basic - Bị khóa do quá hạn (2 ngày trước)',
    position: 41,
    orderCode: 'MKT-LOCK-2024-041',
    status: ORDER_STATUS.LOCKED,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Đơn hàng LOCKED - License bị khóa trên MKT Server do quá hạn 2 ngày',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    licenseStatus: 'LOCKED',
    accountingConfirmed: false,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(5500000, false),
    ...CREATE_LOCKED_DEADLINE_FIELDS(48, PAYMENT_DEADLINE_SOURCE.GLOBAL),
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.LOCKED_ORDER_2,
    name: 'Đơn hàng MKT Premium - Bị khóa do quá hạn (1 tuần trước)',
    position: 42,
    orderCode: 'MKT-LOCK-2024-042',
    status: ORDER_STATUS.LOCKED,
    subtotal: 25000000,
    tax: 2500000,
    discount: 1000000,
    discountPercent: 4.0,
    refundAmount: 0,
    totalAmount: 26500000,
    currency: 'VND',
    note: 'Đơn hàng LOCKED - Khách hàng Silver bị khóa do quá hạn 1 tuần, cần liên hệ urgently',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    licenseStatus: 'LOCKED',
    accountingConfirmed: false,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(26500000, false),
    ...CREATE_LOCKED_DEADLINE_FIELDS(168, PAYMENT_DEADLINE_SOURCE.CUSTOMER_TYPE, 'Payment overdue - customer requested extension but did not pay'),
  },
];

// ============================================
// PREVIOUS MONTH (JANUARY 2026) SEED DATA
// Dữ liệu tháng trước để test leaderboard previousMonthRevenue
// ============================================

// prettier-ignore
export const MKT_ORDER_DATA_SEED_PREV_MONTH_COLUMNS: (keyof MktOrderDataSeed)[] = [
  'id',
  'name',
  'position',
  'orderCode',
  'status',
  'subtotal',
  'tax',
  'discount',
  'discountPercent',
  'refundAmount',
  'totalAmount',
  'currency',
  'note',
  'trialLicense',
  'requireContract',
  'sInvoiceStatus',
  'licenseStatus',
  'metadata',
  'accountingConfirmed',
  'salePaymentConfirmed',
  'accountOwnerId',
  'mktCustomerId',
  'createdById',
  'couponCode',
  'promotionDiscount',
  'appliedPromotions',
  'appliedCombos',
  'comboDiscount',
  'paidAmount',
  'remainingAmount',
  'paymentStatus',
  'paymentDeadline',
  'paymentDeadlineSource',
  'lockedAt',
  'lockedReason',
  'remindersSent',
  'lastReminderAt',
  'completedAt',
  'version',
  'createdAt',
];

// prettier-ignore
export const MKT_ORDER_DATA_SEEDS_PREV_MONTH: MktOrderDataSeed[] = [
  // ── TIM Apple – Top performer tháng 1 (~100M) ──────────────────────────────
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_TIM_1,
    name: 'Đơn hàng MKT Enterprise Suite - Gói doanh nghiệp tháng 1',
    position: 43,
    orderCode: 'MKT-ENT-2026-01-T1',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 40000000,
    tax: 4000000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 44000000,
    currency: 'VND',
    note: 'Gói Enterprise toàn diện cho tập đoàn lớn - tháng 1/2026',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(44000000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-07T10:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-05T09:00:00.000Z')) ?? undefined,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_TIM_2,
    name: 'Đơn hàng MKT Analytics Pro - Phân tích nâng cao tháng 1',
    position: 44,
    orderCode: 'MKT-ANA-2026-01-T2',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 28000000,
    tax: 2800000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 30800000,
    currency: 'VND',
    note: 'Gói phân tích dữ liệu marketing với AI insights - tháng 1/2026',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(30800000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-17T11:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-15T10:30:00.000Z')) ?? undefined,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_TIM_3,
    name: 'Đơn hàng MKT Multi-Channel - Đa nền tảng tháng 1',
    position: 45,
    orderCode: 'MKT-MULTI-2026-01-T3',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 23000000,
    tax: 2300000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 25300000,
    currency: 'VND',
    note: 'Quản lý marketing đa nền tảng social media - tháng 1/2026',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(25300000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-27T15:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-25T14:00:00.000Z')) ?? undefined,
  },

  // ── JONY Ive – Second place (~69M) ─────────────────────────────────────────
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_JONY_1,
    name: 'Đơn hàng MKT Premium Care - Chăm sóc cao cấp tháng 1',
    position: 46,
    orderCode: 'MKT-CARE-2026-01-J1',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 33000000,
    tax: 3300000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 36300000,
    currency: 'VND',
    note: 'Gói chăm sóc khách hàng VIP tháng 1/2026 - Jony phụ trách',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(36300000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-10T10:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-08T09:30:00.000Z')) ?? undefined,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_JONY_2,
    name: 'Đơn hàng MKT White Label - Thương hiệu riêng tháng 1',
    position: 47,
    orderCode: 'MKT-WHITE-2026-01-J2',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 18000000,
    tax: 1800000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 19800000,
    currency: 'VND',
    note: 'Giải pháp white-label cho reseller tháng 1/2026 - Jony phụ trách',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(19800000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-20T12:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-18T11:00:00.000Z')) ?? undefined,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_JONY_3,
    name: 'Đơn hàng MKT Zalo Package - Marketing Zalo tháng 1',
    position: 48,
    orderCode: 'MKT-ZALO-2026-01-J3',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 12000000,
    tax: 1200000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 13200000,
    currency: 'VND',
    note: 'Gói MKT Zalo Business 2 năm tháng 1/2026 - Jony phụ trách',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(13200000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-30T16:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-28T15:00:00.000Z')) ?? undefined,
  },

  // ── PHIL Schiler – Third place (~37M) ──────────────────────────────────────
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_PHIL_1,
    name: 'Đơn hàng MKT Insta Package - Instagram tháng 1',
    position: 49,
    orderCode: 'MKT-INSTA-2026-01-P1',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 15000000,
    tax: 1500000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 16500000,
    currency: 'VND',
    note: 'Gói MKT Insta Pro 2 năm tháng 1/2026 - Phil phụ trách',
    trialLicense: false,
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(16500000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-12T09:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-10T08:00:00.000Z')) ?? undefined,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_PHIL_2,
    name: 'Đơn hàng MKT Viral Package - Viral video tháng 1',
    position: 50,
    orderCode: 'MKT-VIRAL-2026-01-P2',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 11000000,
    tax: 1100000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 12100000,
    currency: 'VND',
    note: 'Gói MKT Viral Basic 1 năm tháng 1/2026 - Phil phụ trách',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(12100000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-22T14:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-20T13:30:00.000Z')) ?? undefined,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_PHIL_3,
    name: 'Đơn hàng MKT Maps Package - Google Maps tháng 1',
    position: 51,
    orderCode: 'MKT-MAPS-2026-01-P3',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 8000000,
    tax: 800000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 8800000,
    currency: 'VND',
    note: 'Gói MKT Maps Basic 1 năm tháng 1/2026 - Phil phụ trách',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(8800000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-30T17:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-28T16:00:00.000Z')) ?? undefined,
  },

  // ── JANE Austen – Fourth place (~13M) ──────────────────────────────────────
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_JANE_1,
    name: 'Đơn hàng MKT Post Package - Đăng bài Facebook tháng 1',
    position: 52,
    orderCode: 'MKT-POST-2026-01-JN1',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 7000000,
    tax: 700000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 7700000,
    currency: 'VND',
    note: 'Gói MKT Post Basic 1 năm tháng 1/2026 - Jane phụ trách',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(7700000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-14T11:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-12T10:00:00.000Z')) ?? undefined,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_PREV_MONTH_IDS.PREV_JANE_2,
    name: 'Đơn hàng MKT Care Package - Chăm sóc tháng 1',
    position: 53,
    orderCode: 'MKT-CARE-2026-01-JN2',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    discountPercent: 0,
    refundAmount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Gói MKT Care Basic 1 năm tháng 1/2026 - Jane phụ trách',
    trialLicense: false,
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    licenseStatus: 'ACTIVE',
    accountingConfirmed: true,
    salePaymentConfirmed: false,
    metadata: null,
    accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE,
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
    createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE,
    ...DEFAULT_PROMOTION_FIELDS,
    ...DEFAULT_COMBO_FIELDS,
    ...CREATE_PAYMENT_FIELDS(5500000, true),
    ...DEFAULT_PAYMENT_DEADLINE_FIELDS,
    completedAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-24T12:00:00.000Z')) ?? null,
    createdAt: DateTimeUtils.toDate(DateTimeUtils.fromISO('2026-01-22T11:30:00.000Z')) ?? undefined,
  },
];

// ============================================
// STAFF DISTRIBUTION & COMPLETED_AT OVERRIDES
// Applied via SQL UPDATE in prefill after INSERT
//
// Distribution:
// - Tim Apple: 10 orders (ID_1 to ID_10) — completedAt in January 2026
// - Jony Ive: 10 orders (ID_11-14, GOLD_1-3, DIAMOND_1-3) — completedAt Jan-Feb bridge
// - Jane Austen: 9 orders (DIAMOND_4-12) — completedAt Feb 2026
// - Phil Schiler: 8 orders (DIAMOND_13-20) — completedAt Feb 2026
// - PROCESSING/LOCKED orders: keep TIM, no completedAt
// ============================================

// prettier-ignore
export const MKT_ORDER_SEED_OVERRIDES: {
  orderId: string;
  accountOwnerId: string;
  createdById: string;
  completedAt: string | null;
}[] = [
  // ── Tim Apple (10 orders) — completedAt January 2026 ──
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_1, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-05T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_2, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-07T11:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_3, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-09T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_4, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-11T14:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_5, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-13T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_6, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-15T15:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_7, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-17T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_8, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-20T11:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_9, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-24T14:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_10, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.TIM, completedAt: '2026-01-28T10:00:00.000Z' },

  // ── Jony Ive (10 orders) — completedAt Jan 15 – Feb 10 ──
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_11, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-01-15T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_12, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-01-20T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_13, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-01-25T11:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.ID_14, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-01-30T14:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_1, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-02-01T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_2, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-02-03T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_3, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-02-05T11:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_1, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-02-07T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_2, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-02-09T14:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_3, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JONY, completedAt: '2026-02-10T10:00:00.000Z' },

  // ── Jane Austen (9 orders) — completedAt Feb 1–18 ──
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_4, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-01T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_5, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-03T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_6, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-05T14:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_7, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-07T11:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_8, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-09T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_9, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-11T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_10, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-13T15:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_11, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-15T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_12, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.JANE, completedAt: '2026-02-18T14:00:00.000Z' },

  // ── Phil Schiler (8 orders) — completedAt Feb 3–20 ──
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_13, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-03T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_14, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-05T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_15, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-07T14:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_16, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-10T09:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_17, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-13T11:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_18, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-15T10:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_19, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-18T14:00:00.000Z' },
  { orderId: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_20, accountOwnerId: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, createdById: WORKSPACE_MEMBER_DATA_SEED_IDS.PHIL, completedAt: '2026-02-20T09:00:00.000Z' },
];
