import { MKT_CUSTOMER_DATA_SEEDS_IDS } from 'src/mkt-core/customer/constants/mkt-customer.constant';
import { ORDER_STATUS, SINVOICE_STATUS } from 'src/mkt-core/order/constants';

// prettier-ignore
export const MKT_ORDER_DATA_SEED_COLUMNS = [
  'id',
  'name',
  'position',
  'orderCode',
  'status',
  'subtotal',
  'tax',
  'discount',
  'totalAmount',
  'currency',
  'note',
  'requireContract',
  'sInvoiceStatus',
  'createdBySource',
  'createdByWorkspaceMemberId',
  'createdByName',
  'mktCustomerId',
];

//prettier-ignore
export const MKT_ORDER_DATA_SEEDS_IDS = {
  ID_1: '774f7b42-e0e6-45b7-9804-ea6b89c0bf8b',
  ID_2: '09f33908-d459-44c3-999e-97f42faf6d30',
  ID_3: '0200e865-6bb2-4645-904c-1ee9fc021c1e',
  ID_4: 'd4a05376-ec12-4f11-92d9-cd5722d70c0b',
  ID_5: '8a361cb9-f40a-4b03-8e02-fdd6e13e8f29',
  ID_6: 'd7cfdf7f-97c8-47ee-a2f9-5eaa8d3af929',
  ID_7: '642c3b7b-6fff-4fbb-a096-7f5432260ed8',
  ID_8: '52dd35b6-2b2a-42e1-be7c-589295a83868',
  ID_9: '28e054f6-4ce2-48aa-93cc-89519a3cf267',
  ID_10: '1899837e-f89f-44ee-8aea-b9a4647cdae7',
  ID_11: '7359947a-4a39-4b45-897f-6fa031b8eab6',
  ID_12: '611d615e-6c3b-4652-9087-e50043ddf260',
  ID_13: 'b9433b83-0e42-4c58-a380-dfd0a69905d7',
  ID_14:"1ddffa25-0386-4153-94c4-db2cf1184394",
  GOLD_ORDER_1:"01f52114-52d6-4e77-8a1a-5cf064ac8451",
GOLD_ORDER_2:"b23758f2-8d3c-45c7-b648-f4f4e6339bf2",
GOLD_ORDER_3:"e231da12-85c6-46a9-977d-ef6daea6aa3f",
DIAMOND_ORDER_1:"a75e9363-dd0c-493b-92bc-e4364f7f9f9b",
DIAMOND_ORDER_2:"18d5e4e1-2a85-4e92-b3a6-93393e971b67",
DIAMOND_ORDER_3:"da13679d-aefd-46f9-b567-ab3582ed65f5",
DIAMOND_ORDER_4:"1fc4325c-2d66-4b80-98cb-07852369147a",
DIAMOND_ORDER_5:"11a8b9db-cdff-4a94-9a3f-de70d753c87b",
DIAMOND_ORDER_6:"7675d910-ce6f-4974-9e8e-63e8f1ddb838",
DIAMOND_ORDER_7:"86293d74-2203-468c-ac24-580a623a8a3d",
DIAMOND_ORDER_8:"15b26e73-17fa-4dc4-a2ca-fcc609c74466",
DIAMOND_ORDER_9:"965972e5-0e61-489a-9ed0-22a790e618b6",
DIAMOND_ORDER_10:"ddcb8b82-52ac-4fa0-86db-c151848f6a6c",
DIAMOND_ORDER_11:"187bfea8-c0cb-4797-9012-e15e6aa13568",
DIAMOND_ORDER_12:"532c46af-36c1-44e5-bfe3-f49ed2f6611d",
DIAMOND_ORDER_13:"984e8a9a-b30e-49d4-9cbd-0ab1329e34f9",
DIAMOND_ORDER_14:"196eb616-07dc-402a-a1eb-611cdab489f3",
DIAMOND_ORDER_15:"f0afcee4-12c3-4beb-9d9f-c7bad67b43d7",
DIAMOND_ORDER_16:"996102ff-b0c2-45f1-b95e-14ffe3d9a262",
DIAMOND_ORDER_17:"b882a0c9-27dd-4cdd-8239-823ec11f3ee4",
DIAMOND_ORDER_18:"37b8f1be-0b69-4768-b5cc-cbda101c3163",
DIAMOND_ORDER_19:"faac3d90-bdb1-4b42-a0c0-88c965eee9ff",
DIAMOND_ORDER_20:"f840d091-cf46-4d5a-99c9-d2259cacd3e3",
};

// prettier-ignore
export const MKT_ORDER_DATA_SEEDS = [
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_1,
    name: 'Đơn hàng MKT Care Package - Gói chăm sóc Facebook',
    position: 1,
    orderCode: 'MKT-CARE-2024-001',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 11000000,
    tax: 1100000,
    discount: 0,
    totalAmount: 12100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Care Basic 1 năm và 2 năm cho khách hàng doanh nghiệp',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.BRONZE_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_2,
    name: 'Đơn hàng MKT Viral Package - Gói viral video',
    position: 2,
    orderCode: 'MKT-VIRAL-2024-002',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 16000000,
    tax: 1600000,
    discount: 500000,
    totalAmount: 17100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Viral Basic 1 năm (2 license) và vĩnh viễn cho agency marketing',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_3,
    name: 'Đơn hàng MKT UID Package - Gói phân tích data',
    position: 3,
    orderCode: 'MKT-UID-2024-003',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 6000000,
    tax: 600000,
    discount: 0,
    totalAmount: 6600000,
    currency: 'VND',
    note: 'Đơn hàng 3 license MKT UID Basic 1 năm cho team phân tích dữ liệu',
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_4,
    name: 'Đơn hàng MKT Insta Package - Gói Instagram marketing',
    position: 4,
    orderCode: 'MKT-INSTA-2024-004',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 15000000,
    tax: 1500000,
    discount: 0,
    totalAmount: 16500000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Insta Basic 2 năm và vĩnh viễn cho influencer marketing',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_5,
    name: 'Đơn hàng MKT Tube Package - Gói quản lý YouTube',
    position: 5,
    orderCode: 'MKT-TUBE-2024-005',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 9000000,
    tax: 900000,
    discount: 0,
    totalAmount: 9900000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Tube Basic 1 năm (2 license) và vĩnh viễn cho MCN',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_6,
    name: 'Đơn hàng MKT Post Package - Gói đăng bài Facebook',
    position: 6,
    orderCode: 'MKT-POST-2024-006',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 3000000,
    tax: 300000,
    discount: 0,
    totalAmount: 3300000,
    currency: 'VND',
    note: 'Đơn hàng MKT Post Basic 1 năm cho shop bán hàng online',
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.SILVER_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_7,
    name: 'Đơn hàng MKT Zalo Package - Gói marketing Zalo',
    position: 7,
    orderCode: 'MKT-ZALO-2024-007',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Đơn hàng MKT Zalo Basic 2 năm cho doanh nghiệp B2B',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_8,
    name: 'Đơn hàng MKT Group Package - Gói quản lý Group Facebook',
    position: 8,
    orderCode: 'MKT-GROUP-2024-008',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 16000000,
    tax: 1600000,
    discount: 1000000,
    totalAmount: 17600000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Group Basic 1 năm (2 license) và vĩnh viễn cho community manager',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_9,
    name: 'Đơn hàng MKT Twitter Package - Gói marketing Twitter/X',
    position: 9,
    orderCode: 'MKT-TWITTER-2024-009',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 3000000,
    tax: 300000,
    discount: 0,
    totalAmount: 3300000,
    currency: 'VND',
    note: 'Đơn hàng MKT Twitter Basic 1 năm - thanh toán thất bại',
    requireContract: false,
    sInvoiceStatus: SINVOICE_STATUS.FAILED,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_10,
    name: 'Đơn hàng MKT Page Package - Gói quản lý Fanpage',
    position: 10,
    orderCode: 'MKT-PAGE-2024-010',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 5000000,
    tax: 500000,
    discount: 0,
    totalAmount: 5500000,
    currency: 'VND',
    note: 'Đơn hàng MKT Page Basic 2 năm cho agency quản lý fanpage',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_11,
    name: 'Đơn hàng MKT Maps Package - Gói scan Google Maps',
    position: 11,
    orderCode: 'MKT-MAPS-2024-011',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 9000000,
    tax: 900000,
    discount: 0,
    totalAmount: 9900000,
    currency: 'VND',
    note: 'Đơn hàng 3 license MKT Maps Basic 1 năm cho team lead generation',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Jane Smith',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_12,
    name: 'Đơn hàng MKT Maps Forever - Gói vĩnh viễn Google Maps',
    position: 12,
    orderCode: 'MKT-MAPS-FOREVER-2024-012',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 10000000,
    tax: 1000000,
    discount: 0,
    totalAmount: 11000000,
    currency: 'VND',
    note: 'Đơn hàng MKT Maps Basic vĩnh viễn cho doanh nghiệp lớn',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Mike Johnson',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_13,
    name: 'Đơn hàng Combo Package - Gói tổng hợp UID + Post',
    position: 13,
    orderCode: 'MKT-COMBO-2024-013',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 8500000,
    tax: 850000,
    discount: 0,
    totalAmount: 9350000,
    currency: 'VND',
    note: 'Đơn hàng combo MKT UID Basic 2 năm + MKT Post Basic 2 năm - đã hủy',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.PENDING,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.ID_14,
    name: 'Đơn hàng MKT Care Package - Gói chăm sóc Facebook',
    position: 14,
    orderCode: 'MKT-CARE-2024-014',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 11000000,
    tax: 1100000,
    discount: 0,
    totalAmount: 12100000,
    currency: 'VND',
    note: 'Đơn hàng gói MKT Care Basic 1 năm và 2 năm cho khách hàng doanh nghiệp',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'John Doe',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
  },
  // GOLD_CUSTOMER orders
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_1,
    name: 'Đơn hàng MKT Premium Care - Gói chăm sóc cao cấp',
    position: 15,
    orderCode: 'MKT-PREMIUM-2024-015',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 25000000,
    tax: 2500000,
    discount: 1000000,
    totalAmount: 26500000,
    currency: 'VND',
    note: 'Gói chăm sóc khách hàng VIP với tư vấn 24/7',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Trần Thị Mai',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_2,
    name: 'Đơn hàng MKT Analytics Pro - Gói phân tích nâng cao',
    position: 16,
    orderCode: 'MKT-ANALYTICS-2024-016',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 18000000,
    tax: 1800000,
    discount: 500000,
    totalAmount: 19300000,
    currency: 'VND',
    note: 'Gói phân tích dữ liệu khách hàng với AI insights',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Trần Thị Mai',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.GOLD_ORDER_3,
    name: 'Đơn hàng MKT Multi-Channel - Gói đa nền tảng',
    position: 17,
    orderCode: 'MKT-MULTI-2024-017',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 22000000,
    tax: 2200000,
    discount: 800000,
    totalAmount: 23400000,
    currency: 'VND',
    note: 'Quản lý marketing trên tất cả nền tảng social media',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Trần Thị Mai',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.GOLD_CUSTOMER,
  },
  // DIAMOND_CUSTOMER orders
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_1,
    name: 'Đơn hàng MKT Enterprise Suite - Gói doanh nghiệp đầy đủ',
    position: 18,
    orderCode: 'MKT-ENT-2024-018',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 500000000,
    tax: 50000000,
    discount: 25000000,
    totalAmount: 525000000,
    currency: 'VND',
    note: 'Giải pháp toàn diện cho doanh nghiệp lớn với dedicated support',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_2,
    name: 'Đơn hàng MKT AI Analytics - Gói phân tích AI cao cấp',
    position: 19,
    orderCode: 'MKT-AI-2024-019',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 300000000,
    tax: 30000000,
    discount: 15000000,
    totalAmount: 315000000,
    currency: 'VND',
    note: 'Phân tích dữ liệu với AI và machine learning',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_3,
    name: 'Đơn hàng MKT Custom Development - Phát triển tùy chỉnh',
    position: 20,
    orderCode: 'MKT-DEV-2024-020',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 800000000,
    tax: 80000000,
    discount: 40000000,
    totalAmount: 840000000,
    currency: 'VND',
    note: 'Phát triển tính năng riêng theo yêu cầu doanh nghiệp',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_4,
    name: 'Đơn hàng MKT Global Expansion - Gói mở rộng quốc tế',
    position: 21,
    orderCode: 'MKT-GLOBAL-2024-021',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 450000000,
    tax: 45000000,
    discount: 20000000,
    totalAmount: 475000000,
    currency: 'VND',
    note: 'Hỗ trợ marketing đa quốc gia với localization',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_5,
    name: 'Đơn hàng MKT White Label - Gói thương hiệu riêng',
    position: 22,
    orderCode: 'MKT-WHITE-2024-022',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 600000000,
    tax: 60000000,
    discount: 30000000,
    totalAmount: 630000000,
    currency: 'VND',
    note: 'Giải pháp white-label cho reseller và partner',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_6,
    name: 'Đơn hàng MKT API Premium - Gói API cao cấp',
    position: 23,
    orderCode: 'MKT-API-2024-023',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 250000000,
    tax: 25000000,
    discount: 12000000,
    totalAmount: 263000000,
    currency: 'VND',
    note: 'API unlimited với rate limit cao cho tích hợp hệ thống',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_7,
    name: 'Đơn hàng MKT Training & Certification - Đào tạo chuyên sâu',
    position: 24,
    orderCode: 'MKT-TRAIN-2024-024',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 120000000,
    tax: 12000000,
    discount: 5000000,
    totalAmount: 127000000,
    currency: 'VND',
    note: 'Chương trình đào tạo và chứng nhận cho team marketing',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_8,
    name: 'Đơn hàng MKT Security Plus - Gói bảo mật nâng cao',
    position: 25,
    orderCode: 'MKT-SEC-2024-025',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 180000000,
    tax: 18000000,
    discount: 8000000,
    totalAmount: 190000000,
    currency: 'VND',
    note: 'Bảo mật cấp enterprise với SSO và audit logs',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_9,
    name: 'Đơn hàng MKT Data Lake - Kho dữ liệu lớn',
    position: 26,
    orderCode: 'MKT-LAKE-2024-026',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 350000000,
    tax: 35000000,
    discount: 17000000,
    totalAmount: 368000000,
    currency: 'VND',
    note: 'Giải pháp lưu trữ và xử lý dữ liệu quy mô lớn',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_10,
    name: 'Đơn hàng MKT Automation Studio - Studio tự động hóa',
    position: 27,
    orderCode: 'MKT-AUTO-2024-027',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 280000000,
    tax: 28000000,
    discount: 14000000,
    totalAmount: 294000000,
    currency: 'VND',
    note: 'Tự động hóa toàn bộ quy trình marketing với workflow',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_11,
    name: 'Đơn hàng MKT Performance Monitoring - Giám sát hiệu suất',
    position: 28,
    orderCode: 'MKT-PERF-2024-028',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 150000000,
    tax: 15000000,
    discount: 7000000,
    totalAmount: 158000000,
    currency: 'VND',
    note: 'Giám sát real-time hiệu suất marketing campaigns',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_12,
    name: 'Đơn hàng MKT Compliance Suite - Gói tuân thủ quy định',
    position: 29,
    orderCode: 'MKT-COMP-2024-029',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 200000000,
    tax: 20000000,
    discount: 10000000,
    totalAmount: 210000000,
    currency: 'VND',
    note: 'Tuân thủ GDPR, CCPA và các quy định bảo mật dữ liệu',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_13,
    name: 'Đơn hàng MKT Mobile SDK - Bộ phát triển mobile',
    position: 30,
    orderCode: 'MKT-SDK-2024-030',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 320000000,
    tax: 32000000,
    discount: 16000000,
    totalAmount: 336000000,
    currency: 'VND',
    note: 'SDK tích hợp marketing cho ứng dụng mobile',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_14,
    name: 'Đơn hàng MKT Edge Computing - Tính toán cạnh',
    position: 31,
    orderCode: 'MKT-EDGE-2024-031',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 400000000,
    tax: 40000000,
    discount: 20000000,
    totalAmount: 420000000,
    currency: 'VND',
    note: 'Xử lý dữ liệu marketing tại edge để giảm latency',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_15,
    name: 'Đơn hàng MKT Blockchain Analytics - Phân tích blockchain',
    position: 32,
    orderCode: 'MKT-BLOCK-2024-032',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 600000000,
    tax: 60000000,
    discount: 30000000,
    totalAmount: 630000000,
    currency: 'VND',
    note: 'Phân tích marketing trong ecosystem blockchain và Web3',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_16,
    name: 'Đơn hàng MKT IoT Integration - Tích hợp IoT',
    position: 33,
    orderCode: 'MKT-IOT-2024-033',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 380000000,
    tax: 38000000,
    discount: 19000000,
    totalAmount: 399000000,
    currency: 'VND',
    note: 'Tích hợp dữ liệu marketing từ thiết bị IoT',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_17,
    name: 'Đơn hàng MKT Quantum Computing - Tính toán lượng tử',
    position: 34,
    orderCode: 'MKT-QUANTUM-2024-034',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 1200000000,
    tax: 120000000,
    discount: 60000000,
    totalAmount: 1260000000,
    currency: 'VND',
    note: 'Ứng dụng quantum computing trong optimization marketing',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_18,
    name: 'Đơn hàng MKT VR/AR Analytics - Phân tích thực tế ảo',
    position: 35,
    orderCode: 'MKT-VR-2024-035',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 500000000,
    tax: 50000000,
    discount: 25000000,
    totalAmount: 525000000,
    currency: 'VND',
    note: 'Phân tích hành vi người dùng trong môi trường VR/AR',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_19,
    name: 'Đơn hàng MKT Neural Networks - Mạng nơ-ron nhân tạo',
    position: 36,
    orderCode: 'MKT-NEURAL-2024-036',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 750000000,
    tax: 75000000,
    discount: 37000000,
    totalAmount: 788000000,
    currency: 'VND',
    note: 'Mạng nơ-ron sâu cho dự đoán hành vi khách hàng',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  },
  {
    id: MKT_ORDER_DATA_SEEDS_IDS.DIAMOND_ORDER_20,
    name: 'Đơn hàng MKT Metaverse Platform - Nền tảng metaverse',
    position: 37,
    orderCode: 'MKT-META-2024-037',
    status: ORDER_STATUS.COMPLETED,
    subtotal: 2000000000,
    tax: 200000000,
    discount: 100000000,
    totalAmount: 2100000000,
    currency: 'VND',
    note: 'Nền tảng marketing toàn diện trong metaverse',
    requireContract: true,
    sInvoiceStatus: SINVOICE_STATUS.SUCCESS,
    createdBySource: 'API',
    createdByWorkspaceMemberId: null,
    createdByName: 'Nguyễn Văn Thành',
    mktCustomerId: MKT_CUSTOMER_DATA_SEEDS_IDS.DIAMOND_CUSTOMER,
  }
];
