import {
  PROMOTION_STATUS,
  PROMOTION_TYPE,
  PROMOTION_DEFAULTS,
  PromotionStatus,
  PromotionType,
} from 'src/mkt-core/mkt-promotion/constants';

type MktPromotionDataSeed = {
  id: string;
  name: string;
  code: string;
  description: string | null;
  status: PromotionStatus;
  promotionType: PromotionType;
  discountValue: number;
  maxDiscountAmount: number | null;
  minOrderAmount: number | null;
  currency: string;
  startDate: Date;
  endDate: Date | null;
  usageLimit: number | null;
  usageLimitPerCustomer: number | null;
  currentUsageCount: number;
  priority: number;
  stackable: boolean;
  isAutoApply: boolean;
  metadata: Record<string, unknown> | null;
};

export const MKT_PROMOTION_DATA_SEED_COLUMNS: (keyof MktPromotionDataSeed)[] = [
  'id',
  'name',
  'code',
  'description',
  'status',
  'promotionType',
  'discountValue',
  'maxDiscountAmount',
  'minOrderAmount',
  'currency',
  'startDate',
  'endDate',
  'usageLimit',
  'usageLimitPerCustomer',
  'currentUsageCount',
  'priority',
  'stackable',
  'isAutoApply',
  'metadata',
];

export const MKT_PROMOTION_DATA_SEEDS_IDS = {
  SUMMER_SALE: 'e1fbc9d2-cdfd-44b3-b958-5d31099e6689',
  NEW_CUSTOMER: 'a3b827df-ca20-4a84-a3be-644b90025a3a',
  VIP_DISCOUNT: 'c270a933-ae55-4b3a-8385-2c09b7cbae36',
  FREE_SHIPPING: 'e921005c-3c99-412a-b284-c5ef00a35259',
  BUY_2_GET_1: '0fe66951-45cc-4531-8059-a9767795c0ad',
  FLASH_SALE: '7ddae680-35c2-4bfc-9d48-0870f1557d32',
  LOYALTY_REWARD: 'db3ab2f8-a507-4ec3-990e-acc1300270ce',
  BULK_ORDER: '3a42c280-40ca-48ae-b035-9f1bc90cce07',
};

export const MKT_PROMOTION_DATA_SEEDS: MktPromotionDataSeed[] = [
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.SUMMER_SALE,
    name: 'Summer Sale 2025',
    code: 'SUMMER25',
    description: 'Khuyến mãi mùa hè 2025 - Giảm 20% cho tất cả đơn hàng',
    status: PROMOTION_STATUS.ACTIVE,
    promotionType: PROMOTION_TYPE.PERCENTAGE,
    discountValue: 20,
    maxDiscountAmount: 5000000,
    minOrderAmount: 1000000,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2025-06-01T00:00:00Z'),
    endDate: new Date('2025-08-31T23:59:59Z'),
    usageLimit: 1000,
    usageLimitPerCustomer: 3,
    currentUsageCount: 150,
    priority: 10,
    stackable: false,
    isAutoApply: false,
    metadata: {
      campaign: 'summer_2025',
      targetSegment: 'all',
    },
  },
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.NEW_CUSTOMER,
    name: 'Welcome New Customer',
    code: 'WELCOME10',
    description: 'Giảm 10% cho khách hàng mới đăng ký',
    status: PROMOTION_STATUS.ACTIVE,
    promotionType: PROMOTION_TYPE.PERCENTAGE,
    discountValue: 10,
    maxDiscountAmount: 2000000,
    minOrderAmount: 500000,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2024-01-01T00:00:00Z'),
    endDate: null,
    usageLimit: null,
    usageLimitPerCustomer: 1,
    currentUsageCount: 500,
    priority: 5,
    stackable: true,
    isAutoApply: true,
    metadata: {
      campaign: 'new_customer_onboarding',
      targetSegment: 'new_customers',
      autoApplyCondition: 'first_order',
    },
  },
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.VIP_DISCOUNT,
    name: 'VIP Diamond Exclusive',
    code: 'VIPDIAMOND',
    description: 'Giảm 500,000đ cho khách hàng VIP Diamond',
    status: PROMOTION_STATUS.ACTIVE,
    promotionType: PROMOTION_TYPE.FIXED_AMOUNT,
    discountValue: 500000,
    maxDiscountAmount: null,
    minOrderAmount: 2000000,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2024-01-01T00:00:00Z'),
    endDate: null,
    usageLimit: null,
    usageLimitPerCustomer: null,
    currentUsageCount: 80,
    priority: 20,
    stackable: true,
    isAutoApply: true,
    metadata: {
      campaign: 'vip_loyalty',
      targetSegment: 'diamond_customers',
      tier: 'DIAMOND',
    },
  },
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.FREE_SHIPPING,
    name: 'Free Shipping Weekend',
    code: 'FREESHIP',
    description: 'Miễn phí vận chuyển cho đơn hàng từ 300,000đ',
    status: PROMOTION_STATUS.ACTIVE,
    promotionType: PROMOTION_TYPE.FREE_SHIPPING,
    discountValue: 0,
    maxDiscountAmount: 100000,
    minOrderAmount: 300000,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2025-01-01T00:00:00Z'),
    endDate: new Date('2025-12-31T23:59:59Z'),
    usageLimit: null,
    usageLimitPerCustomer: 5,
    currentUsageCount: 1200,
    priority: 3,
    stackable: true,
    isAutoApply: true,
    metadata: {
      campaign: 'free_shipping_2025',
      applyDays: ['saturday', 'sunday'],
    },
  },
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.BUY_2_GET_1,
    name: 'Buy 2 Get 1 Free',
    code: 'BUY2GET1',
    description: 'Mua 2 sản phẩm tặng 1 sản phẩm có giá trị thấp nhất',
    status: PROMOTION_STATUS.ACTIVE,
    promotionType: PROMOTION_TYPE.BUY_X_GET_Y,
    discountValue: 1,
    maxDiscountAmount: null,
    minOrderAmount: null,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2025-03-01T00:00:00Z'),
    endDate: new Date('2025-03-31T23:59:59Z'),
    usageLimit: 500,
    usageLimitPerCustomer: 2,
    currentUsageCount: 45,
    priority: 15,
    stackable: false,
    isAutoApply: false,
    metadata: {
      campaign: 'march_promotion',
      buyQuantity: 2,
      freeQuantity: 1,
      freeItemSelection: 'lowest_price',
    },
  },
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.FLASH_SALE,
    name: 'Flash Sale 12.12',
    code: 'FLASH1212',
    description: 'Flash Sale ngày 12/12 - Giảm 30%',
    status: PROMOTION_STATUS.EXPIRED,
    promotionType: PROMOTION_TYPE.PERCENTAGE,
    discountValue: 30,
    maxDiscountAmount: 3000000,
    minOrderAmount: 500000,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2024-12-12T00:00:00Z'),
    endDate: new Date('2024-12-12T23:59:59Z'),
    usageLimit: 200,
    usageLimitPerCustomer: 1,
    currentUsageCount: 200,
    priority: 25,
    stackable: false,
    isAutoApply: false,
    metadata: {
      campaign: 'flash_sale_1212',
      specialEvent: true,
    },
  },
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.LOYALTY_REWARD,
    name: 'Loyalty Points Reward',
    code: 'LOYALTY2025',
    description: 'Đổi 1000 điểm lấy 200,000đ giảm giá',
    status: PROMOTION_STATUS.DRAFT,
    promotionType: PROMOTION_TYPE.FIXED_AMOUNT,
    discountValue: 200000,
    maxDiscountAmount: null,
    minOrderAmount: 500000,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2025-04-01T00:00:00Z'),
    endDate: null,
    usageLimit: null,
    usageLimitPerCustomer: null,
    currentUsageCount: 0,
    priority: 8,
    stackable: true,
    isAutoApply: false,
    metadata: {
      campaign: 'loyalty_program',
      pointsRequired: 1000,
      redemptionType: 'points',
    },
  },
  {
    id: MKT_PROMOTION_DATA_SEEDS_IDS.BULK_ORDER,
    name: 'Bulk Order Discount',
    code: 'BULK15',
    description: 'Giảm 15% cho đơn hàng từ 10 triệu VNĐ',
    status: PROMOTION_STATUS.PAUSED,
    promotionType: PROMOTION_TYPE.PERCENTAGE,
    discountValue: 15,
    maxDiscountAmount: 10000000,
    minOrderAmount: 10000000,
    currency: PROMOTION_DEFAULTS.CURRENCY,
    startDate: new Date('2024-06-01T00:00:00Z'),
    endDate: null,
    usageLimit: null,
    usageLimitPerCustomer: null,
    currentUsageCount: 25,
    priority: 12,
    stackable: false,
    isAutoApply: true,
    metadata: {
      campaign: 'b2b_bulk_orders',
      targetSegment: 'business',
    },
  },
];
