export type UserPermissionTemplates = {
  directTemplates: string[];
  inheritedTemplates: string[];
  hierarchyTemplates: string[];
  departmentTemplates: string[];
  effectivePermissions: string[];
  conflicts: TemplateConflict[];
};

export type CompleteUserContext = {
  hierarchy: UserHierarchy;
  department: DepartmentInfo;
  reporting: ReportingRelationships;
  templates: UserPermissionTemplates;
  metadata: {
    lastUpdated: Date;
    cacheKey: string;
    source: 'CACHE' | 'DATABASE' | 'HYBRID';
  };
};

/**
 * Audit Service Types
 */
export type AuditService = {
  logPermissionCheck(entry: AuditEntry): Promise<void>;
  generateSecurityAlert(alert: SecurityAlert): Promise<void>;
  createComplianceReport(
    request: ComplianceReportRequest,
  ): Promise<ComplianceReport>;
  searchAuditLogs(criteria: AuditSearchCriteria): Promise<AuditSearchResult>;
  exportAuditData(request: AuditExportRequest): Promise<AuditExportResult>;
};

export type AuditEntry = {
  eventType: string;
  userId: string;
  workspaceId: string;
  action: string;
  resourceType: string;
  resourceId?: string;
  result: 'GRANTED' | 'DENIED' | 'ERROR';
  reason: string;
  riskScore: number;
  metadata: Record<string, string | number | boolean | Date>;
  timestamp: Date;
};

export type SecurityAlert = {
  alertType: string;
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  userId: string;
  description: string;
  relatedEvents: string[];
  recommendations: string[];
  autoGenerated: boolean;
  createdAt: Date;
};

export type ComplianceReportRequest = {
  framework: string;
  startDate: Date;
  endDate: Date;
  includeMetrics: boolean;
  includeViolations: boolean;
  format: 'JSON' | 'PDF' | 'CSV';
};

export type ComplianceReport = {
  id: string;
  framework: string;
  period: { start: Date; end: Date };
  metrics: ComplianceMetrics;
  violations: ComplianceViolation[];
  recommendations: string[];
  complianceScore: number;
  generatedAt: Date;
};

export type ComplianceMetrics = {
  totalAccessAttempts: number;
  deniedAccess: number;
  approvedAccess: number;
  emergencyAccess: number;
  sensitiveDataAccess: number;
  crossDepartmentAccess: number;
};

export type ComplianceViolation = {
  type: 'POLICY' | 'PROCEDURE' | 'ACCESS' | 'DATA_HANDLING';
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  description: string;
  userId: string;
  timestamp: Date;
  resolved: boolean;
  remediation: string[];
};

export type AuditSearchCriteria = {
  startDate?: Date;
  endDate?: Date;
  userIds?: string[];
  eventTypes?: string[];
  severities?: string[];
  textSearch?: string;
  limit?: number;
  offset?: number;
};

export type AuditSearchResult = {
  entries: AuditEntry[];
  totalCount: number;
  searchDuration: number;
  aggregations: Record<string, string | number | boolean | Date>;
};

export type AuditExportRequest = {
  criteria: AuditSearchCriteria;
  format: 'JSON' | 'CSV' | 'XML';
  includeMetadata: boolean;
  compression: boolean;
  encryption: boolean;
};

export type AuditExportResult = {
  exportId: string;
  status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED';
  downloadUrl?: string;
  fileSize?: number;
  recordCount?: number;
  error?: string;
  createdAt: Date;
  completedAt?: Date;
};
/**
 * Service Types for Enterprise RBAC
 * Contains all service-related type definitions and contracts
 */

import { HierarchyLevel, DepartmentType } from './hierarchy.types';

/**
 * Cache Service Types
 */
export type CacheService = {
  get<T>(key: string): Promise<T | null>;
  set<T>(key: string, value: T, ttlSeconds?: number): Promise<void>;
  delete(key: string): Promise<boolean>;
  clear(): Promise<void>;
  exists(key: string): Promise<boolean>;
  invalidatePattern(pattern: string): Promise<number>;
  getStats(): Promise<CacheStats>;
};

export type CacheStats = {
  hits: number;
  misses: number;
  hitRate: number;
  size: number;
  memoryUsage: number;
  evictions: number;
};

/**
 * Permission Template Service Types
 */
export type PermissionTemplateService = {
  resolveApplicableTemplates(
    userId: string,
    hierarchyLevel: HierarchyLevel,
  ): Promise<PermissionTemplate[]>;
  evaluateTemplateConflicts(
    templates: PermissionTemplate[],
  ): Promise<TemplateConflictResolution>;
  applyTemplateHierarchy(
    templates: PermissionTemplate[],
    level: HierarchyLevel,
  ): Promise<ResolvedTemplate>;
  cacheTemplate(
    templateId: string,
    template: PermissionTemplate,
  ): Promise<void>;
};

export type PermissionTemplate = {
  id: string;
  name: string;
  type: 'SYSTEM' | 'CUSTOM' | 'INHERITED';
  hierarchyLevel: HierarchyLevel;
  departmentTypes: DepartmentType[];
  permissions: string[];
  restrictions: string[];
  priority: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
};

export type TemplateConflictResolution = {
  hasConflicts: boolean;
  conflicts: TemplateConflict[];
  resolution: 'MERGE' | 'OVERRIDE' | 'DENY' | 'ESCALATE';
  mergedPermissions: string[];
  warnings: string[];
};

export type TemplateConflict = {
  type: 'PERMISSION' | 'RESTRICTION' | 'LEVEL';
  templateIds: string[];
  conflictingItems: string[];
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  autoResolvable: boolean;
};

export type ResolvedTemplate = {
  finalPermissions: string[];
  appliedTemplates: string[];
  inheritanceChain: string[];
  effectiveLevel: HierarchyLevel;
  metadata: Record<string, string | number | boolean | Date>;
};

/**
 * Resource Identification Service Types
 */
export type ResourceIdentificationService = {
  identifyResourceType(objectName: string): Promise<ResourceType>;
  resolveResourceOwnership(
    objectName: string,
    recordId?: string,
  ): Promise<ResourceOwnership>;
  classifyResourceSensitivity(
    objectName: string,
    recordId?: string,
  ): Promise<SensitivityClassification>;
  resolveDependencies(
    objectName: string,
    recordId?: string,
  ): Promise<ResourceDependency[]>;
};

export type ResourceType = {
  type:
    | 'BUSINESS_DATA'
    | 'USER_MGMT'
    | 'FINANCIAL'
    | 'SYSTEM_CONFIG'
    | 'REPORTING';
  category: string;
  subcategory?: string;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  requiresApproval: boolean;
  auditRequired: boolean;
};

export type ResourceOwnership = {
  ownerId?: string;
  ownerType: 'USER' | 'DEPARTMENT' | 'SYSTEM';
  departmentId?: string;
  teamId?: string;
  createdBy?: string;
  lastModifiedBy?: string;
  inheritanceRules: OwnershipInheritance[];
};

export type OwnershipInheritance = {
  sourceType: 'PARENT' | 'CREATOR' | 'DEPARTMENT';
  targetType: 'USER' | 'ROLE' | 'DEPARTMENT';
  permissions: string[];
};

export type SensitivityClassification = {
  level: 'PUBLIC' | 'INTERNAL' | 'CONFIDENTIAL' | 'RESTRICTED' | 'TOP_SECRET';
  dataTypes: string[];
  complianceFrameworks: string[];
  retentionPeriod: number;
  encryptionRequired: boolean;
  accessRestrictions: string[];
};

export type ResourceDependency = {
  dependencyType: 'REQUIRED' | 'BLOCKED_BY' | 'RELATED';
  resourceType: string;
  resourceId?: string;
  relationship: string;
  circular: boolean;
  canBypass: boolean;
};

/**
 * Validation Orchestrator Service Types
 */
export type ValidationOrchestratorService = {
  executeValidation(context: ValidationContext): Promise<ValidationResult>;
  executeSteps(
    context: ValidationContext,
    stepNumbers: number[],
  ): Promise<ValidationResult>;
  getExecutionPlan(context: ValidationContext): Promise<ExecutionPlan>;
  registerStep(step: ValidationStep): void;
  unregisterStep(stepNumber: number): void;
  getPerformanceMetrics(): Promise<OrchestrationMetrics>;
};

export type ValidationContext = {
  userId: string;
  workspaceId: string;
  action: string;
  resourceType: string;
  resourceId?: string;
  metadata: Record<string, string | number | boolean | Date>;
  requestId: string;
  timestamp: Date;
};

export type ValidationResult = {
  allowed: boolean;
  reason: string;
  confidence: number;
  stepResults: StepResult[];
  executionTime: number;
  cacheHit: boolean;
  warnings: string[];
  recommendations: string[];
};

export type StepResult = {
  stepNumber: number;
  stepName: string;
  result: 'PASS' | 'FAIL' | 'SKIP' | 'WARNING' | 'ERROR';
  executionTime: number;
  reason?: string;
  data?: Record<string, string | number | boolean | Date>;
  errors?: string[];
};

export type ExecutionPlan = {
  totalSteps: number;
  estimatedTime: number;
  parallelGroups: number[][];
  dependencies: Record<number, number[]>;
  optimizations: string[];
};

export type ValidationStep = {
  stepNumber: number;
  stepName: string;
  isRequired: boolean;
  canSkip: boolean;
  maxExecutionTime: number;
  dependencies: number[];
  execute(context: ValidationContext): Promise<StepResult>;
};

export type OrchestrationMetrics = {
  totalExecutions: number;
  averageExecutionTime: number;
  successRate: number;
  cacheHitRate: number;
  stepMetrics: Record<number, StepMetrics>;
  errorPatterns: ErrorPattern[];
};

export type StepMetrics = {
  executionCount: number;
  averageTime: number;
  successRate: number;
  errorRate: number;
  skipRate: number;
};

export type ErrorPattern = {
  pattern: string;
  frequency: number;
  lastOccurrence: Date;
  affectedSteps: number[];
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
};

/**
 * User Context Resolution Service Types
 */
export type UserContextResolutionService = {
  resolveUserHierarchy(workspaceMemberId: string): Promise<UserHierarchy>;
  resolveDepartmentInfo(workspaceMemberId: string): Promise<DepartmentInfo>;
  resolveReportingRelationships(
    workspaceMemberId: string,
  ): Promise<ReportingRelationships>;
  resolvePermissionTemplates(
    workspaceMemberId: string,
  ): Promise<UserPermissionTemplates>;
  getUserContext(workspaceMemberId: string): Promise<CompleteUserContext>;
};

export type UserHierarchy = {
  userId: string;
  workspaceMemberId: string;
  hierarchyLevel: HierarchyLevel;
  jobTitle: string;
  isActive: boolean;
  effectiveFrom: Date;
  effectiveTo?: Date;
  specialAuthorities: SpecialAuthority[];
};

export type SpecialAuthority = {
  type: 'FINANCIAL' | 'HR' | 'LEGAL' | 'SECURITY' | 'AUDIT';
  level: 'BASIC' | 'ADVANCED' | 'FULL';
  grantedBy: string;
  grantedAt: Date;
  expiresAt?: Date;
  conditions: string[];
};

export type DepartmentInfo = {
  departmentId: string;
  departmentName: string;
  departmentType: DepartmentType;
  parentDepartmentId?: string;
  headId?: string;
  budgetAccess: boolean;
  crossDepartmentAccess: boolean;
  sensitiveDataAccess: boolean;
};

export type ReportingRelationships = {
  managerId?: string;
  subordinateIds: string[];
  reportingChain: string[];
  peerIds: string[];
  crossDepartmentPeers: string[];
  delegatedAuthorities: DelegatedAuthority[];
};

export type DelegatedAuthority = {
  authorityType: string;
  delegatedBy: string;
  delegatedAt: Date;
  scope: string[];
  limitations: string[];
  expiresAt?: Date;
};
