import { TagColor } from 'src/engine/metadata-modules/field-metadata/dtos/options.input';

export enum ORDER_HISTORY_ACTION {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  PAYMENT_ADDED = 'PAYMENT_ADDED',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  ITEM_ADDED = 'ITEM_ADDED',
  ITEM_REMOVED = 'ITEM_REMOVED',
  ITEM_UPDATED = 'ITEM_UPDATED',
  CUSTOMER_CHANGED = 'CUSTOMER_CHANGED',
  AMOUNT_CHANGED = 'AMOUNT_CHANGED',
  NOTE_ADDED = 'NOTE_ADDED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  LICENSE_ASSIGNED = 'LICENSE_ASSIGNED',
  LICENSE_UPDATED = 'LICENSE_UPDATED',
  CONTRACT_CREATED = 'CONTRACT_CREATED',
  CONTRACT_UPDATED = 'CONTRACT_UPDATED',
  INVOICE_GENERATED = 'INVOICE_GENERATED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  TRIAL_CONVERTED = 'TRIAL_CONVERTED',
  VARIANT_CHANGED = 'VARIANT_CHANGED',
  METADATA_UPDATED = 'METADATA_UPDATED',
  ARCHIVED = 'ARCHIVED',
  RESTORED = 'RESTORED',
}

export const ORDER_HISTORY_ACTION_OPTIONS = [
  {
    value: ORDER_HISTORY_ACTION.CREATED,
    label: 'Created',
    color: 'green' as TagColor,
    position: 0,
  },
  {
    value: ORDER_HISTORY_ACTION.UPDATED,
    label: 'Updated',
    color: 'blue' as TagColor,
    position: 1,
  },
  {
    value: ORDER_HISTORY_ACTION.STATUS_CHANGED,
    label: 'Status Changed',
    color: 'orange' as TagColor,
    position: 2,
  },
  {
    value: ORDER_HISTORY_ACTION.PAYMENT_ADDED,
    label: 'Payment Added',
    color: 'green' as TagColor,
    position: 3,
  },
  {
    value: ORDER_HISTORY_ACTION.PAYMENT_UPDATED,
    label: 'Payment Updated',
    color: 'blue' as TagColor,
    position: 4,
  },
  {
    value: ORDER_HISTORY_ACTION.ITEM_ADDED,
    label: 'Item Added',
    color: 'green' as TagColor,
    position: 5,
  },
  {
    value: ORDER_HISTORY_ACTION.ITEM_REMOVED,
    label: 'Item Removed',
    color: 'red' as TagColor,
    position: 6,
  },
  {
    value: ORDER_HISTORY_ACTION.ITEM_UPDATED,
    label: 'Item Updated',
    color: 'blue' as TagColor,
    position: 7,
  },
  {
    value: ORDER_HISTORY_ACTION.CUSTOMER_CHANGED,
    label: 'Customer Changed',
    color: 'purple' as TagColor,
    position: 8,
  },
  {
    value: ORDER_HISTORY_ACTION.AMOUNT_CHANGED,
    label: 'Amount Changed',
    color: 'yellow' as TagColor,
    position: 9,
  },
  {
    value: ORDER_HISTORY_ACTION.NOTE_ADDED,
    label: 'Note Added',
    color: 'gray' as TagColor,
    position: 10,
  },
  {
    value: ORDER_HISTORY_ACTION.NOTE_UPDATED,
    label: 'Note Updated',
    color: 'gray' as TagColor,
    position: 11,
  },
  {
    value: ORDER_HISTORY_ACTION.LICENSE_ASSIGNED,
    label: 'License Assigned',
    color: 'green' as TagColor,
    position: 12,
  },
  {
    value: ORDER_HISTORY_ACTION.LICENSE_UPDATED,
    label: 'License Updated',
    color: 'blue' as TagColor,
    position: 13,
  },
  {
    value: ORDER_HISTORY_ACTION.CONTRACT_CREATED,
    label: 'Contract Created',
    color: 'green' as TagColor,
    position: 14,
  },
  {
    value: ORDER_HISTORY_ACTION.CONTRACT_UPDATED,
    label: 'Contract Updated',
    color: 'blue' as TagColor,
    position: 15,
  },
  {
    value: ORDER_HISTORY_ACTION.INVOICE_GENERATED,
    label: 'Invoice Generated',
    color: 'green' as TagColor,
    position: 16,
  },
  {
    value: ORDER_HISTORY_ACTION.INVOICE_UPDATED,
    label: 'Invoice Updated',
    color: 'blue' as TagColor,
    position: 17,
  },
  {
    value: ORDER_HISTORY_ACTION.CANCELLED,
    label: 'Cancelled',
    color: 'red' as TagColor,
    position: 18,
  },
  {
    value: ORDER_HISTORY_ACTION.REFUNDED,
    label: 'Refunded',
    color: 'red' as TagColor,
    position: 19,
  },
  {
    value: ORDER_HISTORY_ACTION.TRIAL_CONVERTED,
    label: 'Trial Converted',
    color: 'purple' as TagColor,
    position: 20,
  },
  {
    value: ORDER_HISTORY_ACTION.VARIANT_CHANGED,
    label: 'Variant Changed',
    color: 'orange' as TagColor,
    position: 21,
  },
  {
    value: ORDER_HISTORY_ACTION.METADATA_UPDATED,
    label: 'Metadata Updated',
    color: 'gray' as TagColor,
    position: 22,
  },
  {
    value: ORDER_HISTORY_ACTION.ARCHIVED,
    label: 'Archived',
    color: 'red' as TagColor,
    position: 23,
  },
  {
    value: ORDER_HISTORY_ACTION.RESTORED,
    label: 'Restored',
    color: 'green' as TagColor,
    position: 24,
  },
];
