export enum AppPermission {
  VIEW_REPORT_ALL = 'VIEW_REPORT:*',
  VIEW_DASHBOARD_ALL = 'VIEW_DASHBOARD:*',
  VIEW_DASHBOARD_KPI = 'VIEW_DASHBOARD:KPI',
  VIEW_DASHBOARD_SALES = 'VIEW_DASHBOARD:SALES',
  ADMIN = 'admin',
}
